import type { ContentRecord } from '../content/content.types';
import type { CommentRecord, GuestbookEntryRecord } from '../interactions/interactions.service';

const coverImageUrl = '/images/default-post-cover.png';

export function createDemoContentRecords(): ContentRecord[] {
  return [
    {
      id: 'demo-post-summer-archive',
      title: '把个人站做成长期内容系统',
      type: 'post',
      slug: 'summer-archive-content-system',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-11T08:30:00.000Z',
      createdAt: '2026-06-10T09:12:00.000Z',
      updatedAt: '2026-06-11T08:30:00.000Z',
      summary: '从文章、笔记、日常和项目四条线开始，把个人站做成一个可以长期生长的内容系统。',
      seoTitle: '个人内容平台设计笔记',
      seoDescription: 'Starry Summer 的内容结构、后台写作和公网部署思路。',
      bodyMarkdown: [
        '## 为什么不是普通博客',
        '',
        '普通博客更像文章列表，而长期个人站应该是一套内容资产系统。文章适合完整表达，笔记适合快速记录，日常适合保留现场，项目适合沉淀作品。',
        '',
        '## 我想保留的四条线',
        '',
        '- 文章：完整观点、技术复盘、阶段总结',
        '- 笔记：读书摘录、开发片段、灵感草稿',
        '- 日常：短记录、照片说明、当天状态',
        '- 项目：可持续维护的作品档案',
        '',
        '## 下一步',
        '',
        '先把写作、检索、标签、评论和部署闭环跑通，再慢慢做更复杂的权限、统计和主题系统。',
      ].join('\n'),
      sourceType: 'original',
      sourceUrl: '',
      coverImageUrl,
      coverAltText: '夜色工作台与个人内容系统',
      allowComments: true,
      pinned: true,
      featured: true,
      viewCount: 368,
      likeCount: 42,
      categories: ['平台建设', '写作系统'],
      tags: ['Next.js', 'NestJS', '长期主义', '内容资产'],
      series: ['建站日志'],
    },
    {
      id: 'demo-post-docker-cloud',
      title: '用 Docker 把个人站部署到云服务器',
      type: 'post',
      slug: 'docker-cloud-deployment',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-10T14:20:00.000Z',
      createdAt: '2026-06-10T11:00:00.000Z',
      updatedAt: '2026-06-10T14:20:00.000Z',
      summary: '一台云服务器、一个 docker compose 文件，先把公网访问、数据库和备份链路搭起来。',
      bodyMarkdown: [
        '## V1 部署目标',
        '',
        '个人站第一阶段不需要复杂集群。更重要的是能稳定启动、能备份、能恢复、能看日志。',
        '',
        '```bash',
        'docker compose up -d --build',
        'docker compose ps',
        '```',
        '',
        '## 关键环境变量',
        '',
        '- `PUBLIC_SITE_URL`：公网域名',
        '- `DATABASE_URL`：PostgreSQL 连接',
        '- `SESSION_SECRET`：后台登录会话密钥',
        '- `GITHUB_CLIENT_ID` / `GITHUB_CLIENT_SECRET`：留言登录',
      ].join('\n'),
      sourceType: 'original',
      sourceUrl: '',
      coverImageUrl,
      coverAltText: '云服务器部署记录',
      allowComments: true,
      pinned: false,
      featured: true,
      viewCount: 291,
      likeCount: 33,
      categories: ['部署运维'],
      tags: ['Docker', 'PostgreSQL', '云服务器', '备份'],
      series: ['建站日志'],
    },
    {
      id: 'demo-post-writing-rhythm',
      title: '建立一个不打扰生活的写作节奏',
      type: 'post',
      slug: 'quiet-writing-rhythm',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-09T21:10:00.000Z',
      createdAt: '2026-06-09T18:00:00.000Z',
      updatedAt: '2026-06-09T21:10:00.000Z',
      summary: '写作系统最难的不是编辑器，而是如何让记录动作足够轻，不把生活变成任务。',
      bodyMarkdown: [
        '## 轻一点',
        '',
        '我希望这个站点帮助我记录，而不是提醒我还有多少没完成。',
        '',
        '好的写作节奏应该允许草稿长期存在，允许短笔记先于长文章，允许日常记录不必上升成观点。',
      ].join('\n'),
      sourceType: 'original',
      sourceUrl: '',
      coverImageUrl,
      coverAltText: '安静写作桌面',
      allowComments: true,
      pinned: false,
      featured: false,
      viewCount: 176,
      likeCount: 21,
      categories: ['生活方式', '写作系统'],
      tags: ['写作', '效率', '节奏'],
      series: ['建站日志'],
    },
    {
      id: 'demo-note-markdown-ownership',
      title: 'Markdown 是内容的逃生门',
      type: 'note',
      slug: 'markdown-content-ownership',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-11T06:15:00.000Z',
      createdAt: '2026-06-11T06:00:00.000Z',
      updatedAt: '2026-06-11T06:15:00.000Z',
      summary: '数据库负责运行时体验，Markdown 导入导出负责长期所有权。',
      bodyMarkdown: [
        '## 内容要能带走',
        '',
        '数据库适合检索、权限和互动，但长期内容不能只锁在数据库里。Markdown 足够朴素，也足够稳定。',
      ].join('\n'),
      sourceType: 'original',
      sourceUrl: '',
      allowComments: true,
      pinned: false,
      featured: true,
      viewCount: 133,
      likeCount: 15,
      categories: ['笔记'],
      tags: ['Markdown', '导入导出', '内容所有权'],
      series: ['建站日志'],
    },
    {
      id: 'demo-note-auth-boundary',
      title: '评论只允许 GitHub 登录后提交',
      type: 'note',
      slug: 'github-login-comment-boundary',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-10T22:40:00.000Z',
      createdAt: '2026-06-10T22:20:00.000Z',
      updatedAt: '2026-06-10T22:40:00.000Z',
      summary: '评论需要 GitHub 登录后直接显示，后台负责显示、隐藏和反垃圾管理。',
      bodyMarkdown: '评论公开可读，提交需要 GitHub 登录；发布后直接显示，后台保留显示、隐藏、标为垃圾和删除能力。',
      sourceType: 'original',
      sourceUrl: '',
      allowComments: true,
      pinned: false,
      featured: false,
      viewCount: 94,
      likeCount: 11,
      categories: ['笔记', '安全'],
      tags: ['GitHub OAuth', '直接显示', '反垃圾'],
      series: ['建站日志'],
    },
    {
      id: 'demo-note-home-visual',
      title: '首页背景应该像夜里展开的档案馆',
      type: 'note',
      slug: 'home-visual-archive',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-08T12:00:00.000Z',
      createdAt: '2026-06-08T11:30:00.000Z',
      updatedAt: '2026-06-08T12:00:00.000Z',
      summary: '暗色、星点、玻璃感、内容索引，让首页先有氛围，再有入口。',
      bodyMarkdown: '首页不做传统营销页，而像一个个人档案馆的入口：有视觉氛围，也能快速进入文章、笔记、项目和索引。',
      sourceType: 'original',
      sourceUrl: '',
      allowComments: true,
      pinned: false,
      featured: false,
      viewCount: 81,
      likeCount: 10,
      categories: ['设计'],
      tags: ['首页', '视觉', '暗色主题'],
      series: ['视觉调整'],
    },
    {
      id: 'demo-moment-first-run',
      title: '本地第一次跑起来',
      type: 'moment',
      slug: 'local-first-run',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-11T10:05:00.000Z',
      createdAt: '2026-06-11T10:05:00.000Z',
      updatedAt: '2026-06-11T10:05:00.000Z',
      summary: '看到首页有了内容卡片，比空页面安心很多。',
      bodyMarkdown: '今天先塞一组演示数据，终于能看到文章、笔记、日常和项目混在一起时的真实密度。',
      sourceType: 'original',
      sourceUrl: '',
      allowComments: false,
      pinned: false,
      featured: false,
      viewCount: 62,
      likeCount: 8,
      categories: ['日常'],
      tags: ['本地开发', '演示数据'],
      series: [],
    },
    {
      id: 'demo-moment-late-night',
      title: '凌晨改样式的时候',
      type: 'moment',
      slug: 'late-night-style-tuning',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-09T01:18:00.000Z',
      createdAt: '2026-06-09T01:18:00.000Z',
      updatedAt: '2026-06-09T01:18:00.000Z',
      summary: '导航、背景、按钮这些小东西，放在一起才决定站点的气质。',
      bodyMarkdown: '把后台入口从公共导航里拿掉之后，页面终于少了一点突兀感。很多设计问题不是“大改”，而是把不属于这里的东西挪走。',
      sourceType: 'original',
      sourceUrl: '',
      allowComments: false,
      pinned: false,
      featured: false,
      viewCount: 53,
      likeCount: 7,
      categories: ['日常', '设计'],
      tags: ['UI', '夜间开发'],
      series: [],
    },
    {
      id: 'demo-project-starry-summer',
      title: 'Starry Summer',
      type: 'project',
      slug: 'starry-summer',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-10T08:00:00.000Z',
      createdAt: '2026-06-10T08:00:00.000Z',
      updatedAt: '2026-06-11T09:45:00.000Z',
      summary: '个人内容平台：文章、笔记、日常、项目、评论、后台管理和云服务器部署。',
      bodyMarkdown: [
        '## 项目目标',
        '',
        'Starry Summer 面向单人长期使用：公网展示内容，后台维护文章、笔记、项目和互动。',
        '',
        '## 当前技术栈',
        '',
        '- Next.js',
        '- NestJS',
        '- PostgreSQL',
        '- Redis',
        '- Docker Compose',
      ].join('\n'),
      sourceType: 'original',
      sourceUrl: '',
      coverImageUrl,
      coverAltText: 'Starry Summer 项目封面',
      allowComments: true,
      pinned: false,
      featured: true,
      viewCount: 420,
      likeCount: 58,
      categories: ['项目'],
      tags: ['Next.js', 'NestJS', 'PostgreSQL', 'Docker'],
      series: ['作品档案'],
      project: {
        status: 'active',
        stack: ['Next.js', 'NestJS', 'PostgreSQL', 'Redis', 'Docker'],
        startedAt: '2026-06-10',
        links: {
          repository: 'https://github.com/Aster-H/starry-summer',
        },
      },
    },
    {
      id: 'demo-project-reading-room',
      title: 'Reading Room',
      type: 'project',
      slug: 'reading-room',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-07T15:00:00.000Z',
      createdAt: '2026-06-07T15:00:00.000Z',
      updatedAt: '2026-06-07T16:30:00.000Z',
      summary: '一个整理阅读摘录、主题卡片和后续写作素材的小工具设想。',
      bodyMarkdown: 'Reading Room 目前还是项目构想：把阅读摘录按主题沉淀，并能反向生成写作选题。',
      sourceType: 'original',
      sourceUrl: '',
      allowComments: true,
      pinned: false,
      featured: false,
      viewCount: 88,
      likeCount: 12,
      categories: ['项目', '阅读'],
      tags: ['知识管理', '卡片笔记'],
      series: ['作品档案'],
      project: {
        status: 'paused',
        stack: ['Next.js', 'SQLite'],
        startedAt: '2026-05-20',
      },
    },
    {
      id: 'demo-page-about',
      title: '关于我',
      type: 'page',
      slug: 'about',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-06T09:00:00.000Z',
      createdAt: '2026-06-06T09:00:00.000Z',
      updatedAt: '2026-06-11T08:00:00.000Z',
      summary: '这里是 Starry Summer，一个记录写作、项目和日常的个人内容平台。',
      bodyMarkdown: [
        '## 你好',
        '',
        '这里会慢慢变成我的个人内容档案：文章记录完整想法，笔记收纳过程，日常保留现场，项目展示作品。',
        '',
        '这个站点只有我自己维护，但会尽量做成可以长期公网部署、可备份、可迁移的系统。',
      ].join('\n'),
      sourceType: 'original',
      sourceUrl: '',
      allowComments: false,
      pinned: false,
      featured: false,
      viewCount: 120,
      likeCount: 9,
      categories: ['关于'],
      tags: ['个人介绍', 'Starry Summer'],
      series: [],
    },
  ];
}

export function createDemoGuestbookEntries(): GuestbookEntryRecord[] {
  return [
    {
      id: 'demo-guestbook-1',
      authorName: 'Aster.H',
      body: '首页有内容之后整体感觉出来了，暗色氛围和内容卡片搭在一起更像一个个人档案馆。',
      status: 'approved',
      createdAt: '2026-06-11T11:20:00.000Z',
    },
    {
      id: 'demo-guestbook-2',
      authorName: 'Ada',
      body: '留言需要登录再提交，这个边界很好。公开展示和写入权限分开，后面公网部署会稳很多。',
      status: 'approved',
      createdAt: '2026-06-10T19:40:00.000Z',
    },
    {
      id: 'demo-guestbook-3',
      authorName: 'Summer Reader',
      body: '文章、笔记、项目、日常都有一点样例，浏览路径终于能串起来了。',
      status: 'approved',
      createdAt: '2026-06-09T23:16:00.000Z',
    },
    {
      id: 'demo-guestbook-4',
      authorName: 'GitHub Visitor',
      body: '这个站点如果继续做大，可以把专题和系列做成更强的导航入口。',
      status: 'approved',
      createdAt: '2026-06-08T13:08:00.000Z',
    },
  ];
}

export function createDemoComments(): CommentRecord[] {
  return [
    {
      id: 'demo-comment-1',
      targetType: 'post',
      targetId: 'demo-post-summer-archive',
      authorName: 'Ada',
      body: '把内容分成文章、笔记、日常、项目这四类很清楚，后面专题页会很有用。',
      status: 'approved',
      createdAt: '2026-06-11T12:00:00.000Z',
    },
    {
      id: 'demo-comment-2',
      targetType: 'post',
      targetId: 'demo-post-docker-cloud',
      authorName: 'Ops Note',
      body: '部署文档里可以继续补一段备份恢复演练，云服务器上线前会安心很多。',
      status: 'approved',
      createdAt: '2026-06-10T16:05:00.000Z',
    },
    {
      id: 'demo-comment-3',
      targetType: 'project',
      targetId: 'demo-project-starry-summer',
      authorName: 'Builder',
      body: '项目页能展示技术栈、状态和仓库链接，作为作品档案已经够用了。',
      status: 'approved',
      createdAt: '2026-06-10T10:18:00.000Z',
    },
  ];
}
