import type { ContentRecord } from '../content/content.types';
import type { CommentRecord, GuestbookEntryRecord } from '../interactions/interactions.service';

const coverImageUrl = '/images/default-post-cover.png';

export function createDemoContentRecords(): ContentRecord[] {
  return [
    {
      id: 'demo-post-summer-archive',
      title: '为什么叫 Starry Summer',
      type: 'post',
      slug: 'why-starry-summer',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-14T08:30:00.000Z',
      createdAt: '2026-06-14T08:00:00.000Z',
      updatedAt: '2026-07-17T01:55:32.000Z',
      summary: 'Starry Summer 的名字来自童年夏夜；网站则源于一次大学时期的建站尝试，现在用于集中保存和发布个人内容。',
      seoTitle: '为什么叫 Starry Summer',
      seoDescription: 'Starry Summer 名字的来源、第一版网站停止维护的原因，以及现在重新搭建个人内容平台的实际用途。',
      bodyMarkdown: [
        'Starry Summer 这个名字来自我小时候住处附近的一个公园。',
        '',
        '夏天晚上八九点，我经常和伙伴在公园的草坪和松树旁玩。天黑以后能看到星星、月亮，也能看到附近住户亮起的灯。后来给个人网站取名时，我用了 Starry Summer，指的就是这段具体的夏夜记忆，没有再附加别的含义。',
        '',
        '## 第一版网站为什么停了',
        '',
        '大三时，我想做一个个人网站，也希望给正在找实习的朋友提供一段可以参与和讲清楚的项目经历，于是找了几个朋友一起开发。大家主要分工完成前端和基础功能，项目后来部署上线。',
        '',
        '这版网站就是早期的 Pigs-blog。它上线大约一年，之后没有继续维护。直接原因有两个：域名、服务器、部署和其他服务的续费一年合计超过一千元；团队成员当时都是学生，也很难长期投入维护时间。',
        '',
        '## 为什么重新做',
        '',
        '我平时会写技术文章和笔记，内容曾分散在 Typora、本地文件、语雀和掘金。分散存放带来的问题很具体：不方便统一整理，部分草稿长期没有发布，迁移和备份也要分别处理。',
        '',
        '现在重新做 Starry Summer，是为了把这些内容放在一个自己能控制的平台里。重做过程中，我使用 AI 工具辅助编码和修改。它改变的是开发方式，网站的用途没有变，仍然是个人内容平台。',
        '',
        '## 现在的用途',
        '',
        'Starry Summer 目前是 Aster.H 的个人内容平台，用来公开文章、笔记、片刻、项目记录、推荐分享和刷题日记，也提供分类、标签、系列、归档、搜索、RSS 和留言等功能。',
        '',
        '公开内容和站点配置优先保存在 GitHub 仓库中，由 Vercel 部署。内容变更可以随 Git 记录版本，也能直接备份、回滚和迁移；当前公开站不依赖数据库保存这些内容。',
      ].join('\n'),
      sourceType: 'original',
      sourceUrl: '',
      coverImageUrl: '/images/starry-summer-night.png',
      coverAltText: '夏夜公园里的月亮、星星和松树',
      allowComments: true,
      pinned: true,
      featured: true,
      viewCount: 368,
      likeCount: 42,
      categories: ['随笔', '关于'],
      tags: ['Starry Summer', '童年', '夏夜', '个人站'],
      series: ['建站日志'],
    },
    {
      id: 'demo-post-vercel-publishing',
      title: '用 Vercel 和 GitHub 发布个人站',
      type: 'post',
      slug: 'vercel-repository-publishing',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-10T14:20:00.000Z',
      createdAt: '2026-06-10T11:00:00.000Z',
      updatedAt: '2026-06-10T14:20:00.000Z',
      summary: '把公开站点交给 Vercel，把内容和资源留在 GitHub 仓库里。',
      bodyMarkdown: [
        '## 默认部署目标',
        '',
        '个人站第一阶段不需要复杂集群。更重要的是内容可版本化、部署能自动触发、以后迁移不被服务端状态绑住。',
        '',
        '```bash',
        'npm run build',
        'npm run ops:smoke -- https://blog.example.com',
        '```',
        '',
        '## 关键环境变量',
        '',
        '- `PUBLIC_SITE_URL`：公网域名',
        '- `SESSION_SECRET`：后台登录会话密钥',
        '- `GITHUB_CONTENT_TOKEN`：仓库内容发布令牌',
        '- `GITHUB_CLIENT_ID` / `GITHUB_CLIENT_SECRET`：留言登录',
      ].join('\n'),
      sourceType: 'original',
      sourceUrl: '',
      coverImageUrl,
      coverAltText: 'Vercel 部署记录',
      allowComments: true,
      pinned: false,
      featured: true,
      viewCount: 291,
      likeCount: 33,
      categories: ['部署运维'],
      tags: ['Vercel', 'GitHub', '仓库发布', '备份'],
      series: ['建站日志'],
    },
    {
      id: 'demo-post-writing-rhythm',
      title: '建立一个不打扰生活的写作节奏',
      type: 'post',
      slug: 'quiet-writing-rhythm',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-09T21:10:00.000Z',
      createdAt: '2026-06-09T18:00:00.000Z',
      updatedAt: '2026-06-09T21:10:00.000Z',
      summary: '写作系统最难的不是编辑器，而是如何让记录动作足够轻，不把生活变成任务。',
      bodyMarkdown: [
        '## 轻一点',
        '',
        '我希望这个站点帮助我记录，而不是提醒我还有多少没完成。',
        '',
        '好的写作节奏应该允许草稿长期存在，允许短笔记先于长文章，允许日常记录不必上升成观点。',
      ].join('\n'),
      sourceType: 'original',
      sourceUrl: '',
      coverImageUrl,
      coverAltText: '安静写作桌面',
      allowComments: true,
      pinned: false,
      featured: false,
      viewCount: 176,
      likeCount: 21,
      categories: ['生活方式', '写作系统'],
      tags: ['写作', '效率', '节奏'],
      series: ['建站日志'],
    },
    {
      id: 'demo-note-markdown-ownership',
      title: 'Markdown 是内容的逃生门',
      type: 'note',
      slug: 'markdown-content-ownership',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-11T06:15:00.000Z',
      createdAt: '2026-06-11T06:00:00.000Z',
      updatedAt: '2026-06-11T06:15:00.000Z',
      summary: '数据库负责运行时体验，Markdown 导入导出负责长期所有权。',
      bodyMarkdown: [
        '## 内容要能带走',
        '',
        '数据库适合检索、权限和互动，但长期内容不能只锁在数据库里。Markdown 足够朴素，也足够稳定。',
      ].join('\n'),
      sourceType: 'original',
      sourceUrl: '',
      allowComments: true,
      pinned: false,
      featured: true,
      viewCount: 133,
      likeCount: 15,
      categories: ['笔记'],
      tags: ['Markdown', '导入导出', '内容所有权'],
      series: ['建站日志'],
    },
    {
      id: 'demo-note-auth-boundary',
      title: '评论只允许 GitHub 登录后提交',
      type: 'note',
      slug: 'github-login-comment-boundary',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-10T22:40:00.000Z',
      createdAt: '2026-06-10T22:20:00.000Z',
      updatedAt: '2026-06-10T22:40:00.000Z',
      summary: '评论需要 GitHub 登录后直接显示，后台负责显示、隐藏和反垃圾管理。',
      bodyMarkdown: '评论公开可读，提交需要 GitHub 登录；发布后直接显示，后台保留显示、隐藏、标为垃圾和删除能力。',
      sourceType: 'original',
      sourceUrl: '',
      allowComments: true,
      pinned: false,
      featured: false,
      viewCount: 94,
      likeCount: 11,
      categories: ['笔记', '安全'],
      tags: ['GitHub OAuth', '直接显示', '反垃圾'],
      series: ['建站日志'],
    },
    {
      id: 'demo-note-home-visual',
      title: '首页背景应该像夜里展开的档案馆',
      type: 'note',
      slug: 'home-visual-archive',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-08T12:00:00.000Z',
      createdAt: '2026-06-08T11:30:00.000Z',
      updatedAt: '2026-06-08T12:00:00.000Z',
      summary: '暗色、星点、玻璃感、内容索引，让首页先有氛围，再有入口。',
      bodyMarkdown: '首页不做传统营销页，而像一个个人档案馆的入口：有视觉氛围，也能快速进入文章、笔记、项目和索引。',
      sourceType: 'original',
      sourceUrl: '',
      allowComments: true,
      pinned: false,
      featured: false,
      viewCount: 81,
      likeCount: 10,
      categories: ['设计'],
      tags: ['首页', '视觉', '暗色主题'],
      series: ['视觉调整'],
    },
    {
      id: 'demo-moment-first-run',
      title: '本地第一次跑起来',
      type: 'moment',
      slug: 'local-first-run',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-11T10:05:00.000Z',
      createdAt: '2026-06-11T10:05:00.000Z',
      updatedAt: '2026-06-11T10:05:00.000Z',
      summary: '看到首页有了内容卡片，比空页面安心很多。',
      bodyMarkdown: '今天先塞一组演示数据，终于能看到文章、笔记、日常和项目混在一起时的真实密度。',
      sourceType: 'original',
      sourceUrl: '',
      allowComments: false,
      pinned: false,
      featured: false,
      viewCount: 62,
      likeCount: 8,
      categories: ['日常'],
      tags: ['本地开发', '演示数据'],
      series: [],
    },
    {
      id: 'demo-moment-late-night',
      title: '凌晨改样式的时候',
      type: 'moment',
      slug: 'late-night-style-tuning',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-09T01:18:00.000Z',
      createdAt: '2026-06-09T01:18:00.000Z',
      updatedAt: '2026-06-09T01:18:00.000Z',
      summary: '导航、背景、按钮这些小东西，放在一起才决定站点的气质。',
      bodyMarkdown: '把后台入口从公共导航里拿掉之后，页面终于少了一点突兀感。很多设计问题不是“大改”，而是把不属于这里的东西挪走。',
      sourceType: 'original',
      sourceUrl: '',
      allowComments: false,
      pinned: false,
      featured: false,
      viewCount: 53,
      likeCount: 7,
      categories: ['日常', '设计'],
      tags: ['UI', '夜间开发'],
      series: [],
    },
    {
      id: 'demo-project-starry-summer',
      title: 'Starry Summer',
      type: 'project',
      slug: 'starry-summer',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-10T08:00:00.000Z',
      createdAt: '2026-06-10T08:00:00.000Z',
      updatedAt: '2026-06-11T09:45:00.000Z',
      summary: '个人内容平台：文章、笔记、日常、项目、评论、后台管理和仓库发布。',
      bodyMarkdown: [
        '## 项目目标',
        '',
        'Starry Summer 面向单人长期使用：公网展示内容，后台维护文章、笔记、项目和互动。',
        '',
        '## 当前技术栈',
        '',
        '- Next.js',
        '- Repository JSON',
        '- Markdown',
        '- GitHub API',
        '- Vercel',
      ].join('\n'),
      sourceType: 'original',
      sourceUrl: '',
      coverImageUrl,
      coverAltText: 'Starry Summer 项目封面',
      allowComments: true,
      pinned: false,
      featured: true,
      viewCount: 420,
      likeCount: 58,
      categories: ['项目'],
      tags: ['Next.js', 'Markdown', 'Repository JSON', 'Vercel'],
      series: ['作品档案'],
      project: {
        status: 'active',
        stack: ['Next.js', 'Markdown', 'Repository JSON', 'GitHub API', 'Vercel'],
        startedAt: '2026-06-10',
        links: {
          repository: 'https://github.com/Aster-H/starry-summer',
        },
      },
    },
    {
      id: 'demo-project-reading-room',
      title: 'Reading Room',
      type: 'project',
      slug: 'reading-room',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-07T15:00:00.000Z',
      createdAt: '2026-06-07T15:00:00.000Z',
      updatedAt: '2026-06-07T16:30:00.000Z',
      summary: '一个整理阅读摘录、主题卡片和后续写作素材的小工具设想。',
      bodyMarkdown: 'Reading Room 目前还是项目构想：把阅读摘录按主题沉淀，并能反向生成写作选题。',
      sourceType: 'original',
      sourceUrl: '',
      allowComments: true,
      pinned: false,
      featured: false,
      viewCount: 88,
      likeCount: 12,
      categories: ['项目', '阅读'],
      tags: ['知识管理', '卡片笔记'],
      series: ['作品档案'],
      project: {
        status: 'paused',
        stack: ['Next.js', 'SQLite'],
        startedAt: '2026-05-20',
      },
    },
    {
      id: 'demo-page-about',
      title: '关于我',
      type: 'page',
      slug: 'about',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-06T09:00:00.000Z',
      createdAt: '2026-06-06T09:00:00.000Z',
      updatedAt: '2026-06-11T08:00:00.000Z',
      summary: '这里是 Starry Summer，一个记录写作、项目和日常的个人内容平台。',
      bodyMarkdown: [
        '## 你好',
        '',
        '这里会慢慢变成我的个人内容档案：文章记录完整想法，笔记收纳过程，日常保留现场，项目展示作品。',
        '',
        '这个站点只有我自己维护，但会尽量做成可以长期公网部署、可备份、可迁移的系统。',
      ].join('\n'),
      sourceType: 'original',
      sourceUrl: '',
      allowComments: false,
      pinned: false,
      featured: false,
      viewCount: 120,
      likeCount: 9,
      categories: ['关于'],
      tags: ['个人介绍', 'Starry Summer'],
      series: [],
    },
  ];
}

export function createDemoGuestbookEntries(): GuestbookEntryRecord[] {
  return [
    {
      id: 'demo-guestbook-1',
      authorName: 'Aster.H',
      body: '首页有内容之后整体感觉出来了，暗色氛围和内容卡片搭在一起更像一个个人档案馆。',
      status: 'approved',
      createdAt: '2026-06-11T11:20:00.000Z',
    },
    {
      id: 'demo-guestbook-2',
      authorName: 'Ada',
      body: '留言需要登录再提交，这个边界很好。公开展示和写入权限分开，后面公网部署会稳很多。',
      status: 'approved',
      createdAt: '2026-06-10T19:40:00.000Z',
    },
    {
      id: 'demo-guestbook-3',
      authorName: 'Summer Reader',
      body: '文章、笔记、项目、日常都有一点样例，浏览路径终于能串起来了。',
      status: 'approved',
      createdAt: '2026-06-09T23:16:00.000Z',
    },
    {
      id: 'demo-guestbook-4',
      authorName: 'GitHub Visitor',
      body: '这个站点如果继续做大，可以把专题和系列做成更强的导航入口。',
      status: 'approved',
      createdAt: '2026-06-08T13:08:00.000Z',
    },
  ];
}

export function createDemoComments(): CommentRecord[] {
  return [
    {
      id: 'demo-comment-1',
      targetType: 'post',
      targetId: 'demo-post-summer-archive',
      authorName: 'Ada',
      body: '这个名字的来源很适合放在第一篇，星空、夏夜和暖光一下子把站点气质立住了。',
      status: 'approved',
      createdAt: '2026-06-11T12:00:00.000Z',
    },
    {
      id: 'demo-comment-2',
      targetType: 'post',
      targetId: 'demo-post-vercel-publishing',
      authorName: 'Ops Note',
      body: '部署文档里可以继续补一段备份恢复演练，Vercel 上线前会安心很多。',
      status: 'approved',
      createdAt: '2026-06-10T16:05:00.000Z',
    },
    {
      id: 'demo-comment-3',
      targetType: 'project',
      targetId: 'demo-project-starry-summer',
      authorName: 'Builder',
      body: '项目页能展示技术栈、状态和仓库链接，作为作品档案已经够用了。',
      status: 'approved',
      createdAt: '2026-06-10T10:18:00.000Z',
    },
  ];
}
