import type { ContentRecord } from '../content/content.types';
import type { CommentRecord, GuestbookEntryRecord } from '../interactions/interactions.service';

const coverImageUrl = '/images/default-post-cover.png';

export function createDemoContentRecords(): ContentRecord[] {
  return [
    {
      id: 'demo-post-summer-archive',
      title: '为什么叫 Starry Summer',
      type: 'post',
      slug: 'why-starry-summer',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-14T08:30:00.000Z',
      createdAt: '2026-06-14T08:00:00.000Z',
      updatedAt: '2026-06-14T08:30:00.000Z',
      summary: '这个名字来自童年夏夜的公园、草坪、松树、月光、星空，以及回家路上远处院子里亮着的暖光。',
      seoTitle: '为什么叫 Starry Summer',
      seoDescription: 'Starry Summer 这个名字背后的童年夏夜、公园草坪、星空和暖光。',
      bodyMarkdown: [
        '这个名字来自我小时候的一段记忆。',
        '',
        '那时候我家住在一个公园附近。那里有一片草坪，草坪上有松树，分散着长着，不是整齐的那种。',
        '',
        '晚上月光洒在公园里面，草坪会显出一种很深的绿色，亮的地方像蒙了一层薄薄的银光，暗的地方又安静地沉下去。松树的树冠很高，枝叶被风吹得轻轻晃，影子落在草地和小路上，一块一块的。公园里还有石头铺成的小路，不算平整，走上去会有一点高低起伏，月光照在石头边缘的时候，能看出一条弯弯绕绕的路通向更暗的地方。',
        '',
        '夏天傍晚八九点，我经常和小伙伴去那里玩，捉迷藏、跑来跑去，一直到天黑下来。',
        '',
        '有时候大家一起回家，有时候有人先被叫走，我就慢慢跟在后面，或者自己再待一会儿。',
        '',
        '玩完之后，我有时会直接躺在草坪上，有时是往回家的路上走一段，又停下来。',
        '',
        '抬头的时候能看到星星，月亮在头顶上，云会慢慢飘过去。风从松树之间穿过去，草地有一点凉。',
        '',
        '偶尔会听到鸟叫，还没完全安静下来。',
        '',
        '院子里会亮灯，一户一户的，黄色的光从窗户里透出来，不刺眼，但很明显。看得到家里有人在。',
        '',
        '有时候我就不说话，躺一会儿，或者慢慢走回去。',
        '',
        '那时候不会觉得时间很长，但也没人催。',
        '',
        '后来长大以后，去过很多地方，也见过很多夜晚。但很少再有那种感觉：不用做什么，也不用想什么，但知道自己是安全的，家就在旁边。',
        '',
        '所以我把它叫做 Starry Summer。',
        '',
        '它不是一个很完整的概念，更像一个场景：夏天的晚上，玩完之后，草坪还有点凉，风在吹，院子里的灯还亮着。我在回家的路上，或者在草地上多待了一会儿。',
        '',
        '## 为什么又做这个网站',
        '',
        '其实很早以前，我就想做一个个人网站。',
        '',
        '大三的时候，同学们开始找实习，有些人手里还没有可以拿出来讲的项目。那时候我已经有了一些实习经历，也做过一些项目，知道项目经历对找实习有多重要。正好我也一直想做一个自己的站点，就拉了几个朋友一起做。当时还没有现在这样的 AI 工具，开发和维护都要靠人一点点写。我们缺人，就让几个朋友主要负责前端，慢慢把页面和功能搭起来。',
        '',
        '但后来发现，一个网站真正麻烦的地方不只是做出来。功能越多，维护越复杂。第一年的域名和服务器还算便宜，勉强可以接受；但继续往后，域名、服务器、部署和各种服务的续费加起来，一年已经要上千。那时候大家也都还是学生，长期维护的成本和精力都不太现实。网站部署了一年，最后还是停掉了。',
        '',
        '第一版网站其实就是那个早期的 [Pigs-blog](https://github.com/HuangJingwang/Pigs-blog/tree/dev/server)。现在回头看，它不算成熟，但确实是我第一次认真把“个人网站”这件事做成一个能部署、能访问、能让别人一起参与的项目。',
        '',
        '现在重新把它做起来，是因为条件变了。',
        '',
        '有了 AI 之后，很多以前需要反复查、反复改、反复维护的东西，都可以更轻一点地推进。我不再需要把所有精力都耗在基础功能和样式细节上，也更有可能长期维护一个真正属于自己的内容平台。',
        '',
        '平常我会写一些技术博客和笔记。以前更多是用 Typora 写在本地，只能自己看；也会把一些内容放到语雀、掘金，或者散落在本地笔记里。它们都能记录东西，但时间久了，内容会分散，很多想法也就停在了草稿状态。',
        '',
        '所以我想重新做 Starry Summer。',
        '',
        '它会收纳我的笔记、文章和一些零散的思考。我可以先把想法写下来，再慢慢整理、润色，最后沉淀成可以公开阅读的文章。它不需要一开始就很完整，也不需要急着证明什么。只要能长期留下来，就已经很好。',
        '',
        '这个网站以后会写一些东西，不局限主题，也不急着变成什么明确的样子。',
        '',
        '名字只是提醒我，有些东西可以慢一点。可以先留下来，不用急着解释。',
      ].join('\n'),
      sourceType: 'original',
      sourceUrl: '',
      coverImageUrl: '/images/starry-summer-night.png',
      coverAltText: '月光、云和松树枝下的夏夜星空',
      allowComments: true,
      pinned: true,
      featured: true,
      viewCount: 368,
      likeCount: 42,
      categories: ['随笔', '关于'],
      tags: ['Starry Summer', '童年', '夏夜', '个人站'],
      series: ['建站日志'],
    },
    {
      id: 'demo-post-docker-cloud',
      title: '用 Docker 把个人站部署到云服务器',
      type: 'post',
      slug: 'docker-cloud-deployment',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-10T14:20:00.000Z',
      createdAt: '2026-06-10T11:00:00.000Z',
      updatedAt: '2026-06-10T14:20:00.000Z',
      summary: '一台云服务器、一个 docker compose 文件，先把公网访问、数据库和备份链路搭起来。',
      bodyMarkdown: [
        '## V1 部署目标',
        '',
        '个人站第一阶段不需要复杂集群。更重要的是能稳定启动、能备份、能恢复、能看日志。',
        '',
        '```bash',
        'docker compose up -d --build',
        'docker compose ps',
        '```',
        '',
        '## 关键环境变量',
        '',
        '- `PUBLIC_SITE_URL`：公网域名',
        '- `DATABASE_URL`：PostgreSQL 连接',
        '- `SESSION_SECRET`：后台登录会话密钥',
        '- `GITHUB_CLIENT_ID` / `GITHUB_CLIENT_SECRET`：留言登录',
      ].join('\n'),
      sourceType: 'original',
      sourceUrl: '',
      coverImageUrl,
      coverAltText: '云服务器部署记录',
      allowComments: true,
      pinned: false,
      featured: true,
      viewCount: 291,
      likeCount: 33,
      categories: ['部署运维'],
      tags: ['Docker', 'PostgreSQL', '云服务器', '备份'],
      series: ['建站日志'],
    },
    {
      id: 'demo-post-writing-rhythm',
      title: '建立一个不打扰生活的写作节奏',
      type: 'post',
      slug: 'quiet-writing-rhythm',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-09T21:10:00.000Z',
      createdAt: '2026-06-09T18:00:00.000Z',
      updatedAt: '2026-06-09T21:10:00.000Z',
      summary: '写作系统最难的不是编辑器，而是如何让记录动作足够轻，不把生活变成任务。',
      bodyMarkdown: [
        '## 轻一点',
        '',
        '我希望这个站点帮助我记录，而不是提醒我还有多少没完成。',
        '',
        '好的写作节奏应该允许草稿长期存在，允许短笔记先于长文章，允许日常记录不必上升成观点。',
      ].join('\n'),
      sourceType: 'original',
      sourceUrl: '',
      coverImageUrl,
      coverAltText: '安静写作桌面',
      allowComments: true,
      pinned: false,
      featured: false,
      viewCount: 176,
      likeCount: 21,
      categories: ['生活方式', '写作系统'],
      tags: ['写作', '效率', '节奏'],
      series: ['建站日志'],
    },
    {
      id: 'demo-note-markdown-ownership',
      title: 'Markdown 是内容的逃生门',
      type: 'note',
      slug: 'markdown-content-ownership',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-11T06:15:00.000Z',
      createdAt: '2026-06-11T06:00:00.000Z',
      updatedAt: '2026-06-11T06:15:00.000Z',
      summary: '数据库负责运行时体验，Markdown 导入导出负责长期所有权。',
      bodyMarkdown: [
        '## 内容要能带走',
        '',
        '数据库适合检索、权限和互动，但长期内容不能只锁在数据库里。Markdown 足够朴素，也足够稳定。',
      ].join('\n'),
      sourceType: 'original',
      sourceUrl: '',
      allowComments: true,
      pinned: false,
      featured: true,
      viewCount: 133,
      likeCount: 15,
      categories: ['笔记'],
      tags: ['Markdown', '导入导出', '内容所有权'],
      series: ['建站日志'],
    },
    {
      id: 'demo-note-auth-boundary',
      title: '评论只允许 GitHub 登录后提交',
      type: 'note',
      slug: 'github-login-comment-boundary',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-10T22:40:00.000Z',
      createdAt: '2026-06-10T22:20:00.000Z',
      updatedAt: '2026-06-10T22:40:00.000Z',
      summary: '评论需要 GitHub 登录后直接显示，后台负责显示、隐藏和反垃圾管理。',
      bodyMarkdown: '评论公开可读，提交需要 GitHub 登录；发布后直接显示，后台保留显示、隐藏、标为垃圾和删除能力。',
      sourceType: 'original',
      sourceUrl: '',
      allowComments: true,
      pinned: false,
      featured: false,
      viewCount: 94,
      likeCount: 11,
      categories: ['笔记', '安全'],
      tags: ['GitHub OAuth', '直接显示', '反垃圾'],
      series: ['建站日志'],
    },
    {
      id: 'demo-note-home-visual',
      title: '首页背景应该像夜里展开的档案馆',
      type: 'note',
      slug: 'home-visual-archive',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-08T12:00:00.000Z',
      createdAt: '2026-06-08T11:30:00.000Z',
      updatedAt: '2026-06-08T12:00:00.000Z',
      summary: '暗色、星点、玻璃感、内容索引，让首页先有氛围，再有入口。',
      bodyMarkdown: '首页不做传统营销页，而像一个个人档案馆的入口：有视觉氛围，也能快速进入文章、笔记、项目和索引。',
      sourceType: 'original',
      sourceUrl: '',
      allowComments: true,
      pinned: false,
      featured: false,
      viewCount: 81,
      likeCount: 10,
      categories: ['设计'],
      tags: ['首页', '视觉', '暗色主题'],
      series: ['视觉调整'],
    },
    {
      id: 'demo-moment-first-run',
      title: '本地第一次跑起来',
      type: 'moment',
      slug: 'local-first-run',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-11T10:05:00.000Z',
      createdAt: '2026-06-11T10:05:00.000Z',
      updatedAt: '2026-06-11T10:05:00.000Z',
      summary: '看到首页有了内容卡片，比空页面安心很多。',
      bodyMarkdown: '今天先塞一组演示数据，终于能看到文章、笔记、日常和项目混在一起时的真实密度。',
      sourceType: 'original',
      sourceUrl: '',
      allowComments: false,
      pinned: false,
      featured: false,
      viewCount: 62,
      likeCount: 8,
      categories: ['日常'],
      tags: ['本地开发', '演示数据'],
      series: [],
    },
    {
      id: 'demo-moment-late-night',
      title: '凌晨改样式的时候',
      type: 'moment',
      slug: 'late-night-style-tuning',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-09T01:18:00.000Z',
      createdAt: '2026-06-09T01:18:00.000Z',
      updatedAt: '2026-06-09T01:18:00.000Z',
      summary: '导航、背景、按钮这些小东西，放在一起才决定站点的气质。',
      bodyMarkdown: '把后台入口从公共导航里拿掉之后，页面终于少了一点突兀感。很多设计问题不是“大改”，而是把不属于这里的东西挪走。',
      sourceType: 'original',
      sourceUrl: '',
      allowComments: false,
      pinned: false,
      featured: false,
      viewCount: 53,
      likeCount: 7,
      categories: ['日常', '设计'],
      tags: ['UI', '夜间开发'],
      series: [],
    },
    {
      id: 'demo-project-starry-summer',
      title: 'Starry Summer',
      type: 'project',
      slug: 'starry-summer',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-10T08:00:00.000Z',
      createdAt: '2026-06-10T08:00:00.000Z',
      updatedAt: '2026-06-11T09:45:00.000Z',
      summary: '个人内容平台：文章、笔记、日常、项目、评论、后台管理和云服务器部署。',
      bodyMarkdown: [
        '## 项目目标',
        '',
        'Starry Summer 面向单人长期使用：公网展示内容，后台维护文章、笔记、项目和互动。',
        '',
        '## 当前技术栈',
        '',
        '- Next.js',
        '- NestJS',
        '- PostgreSQL',
        '- Redis',
        '- Docker Compose',
      ].join('\n'),
      sourceType: 'original',
      sourceUrl: '',
      coverImageUrl,
      coverAltText: 'Starry Summer 项目封面',
      allowComments: true,
      pinned: false,
      featured: true,
      viewCount: 420,
      likeCount: 58,
      categories: ['项目'],
      tags: ['Next.js', 'NestJS', 'PostgreSQL', 'Docker'],
      series: ['作品档案'],
      project: {
        status: 'active',
        stack: ['Next.js', 'NestJS', 'PostgreSQL', 'Redis', 'Docker'],
        startedAt: '2026-06-10',
        links: {
          repository: 'https://github.com/Aster-H/starry-summer',
        },
      },
    },
    {
      id: 'demo-project-reading-room',
      title: 'Reading Room',
      type: 'project',
      slug: 'reading-room',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-07T15:00:00.000Z',
      createdAt: '2026-06-07T15:00:00.000Z',
      updatedAt: '2026-06-07T16:30:00.000Z',
      summary: '一个整理阅读摘录、主题卡片和后续写作素材的小工具设想。',
      bodyMarkdown: 'Reading Room 目前还是项目构想：把阅读摘录按主题沉淀，并能反向生成写作选题。',
      sourceType: 'original',
      sourceUrl: '',
      allowComments: true,
      pinned: false,
      featured: false,
      viewCount: 88,
      likeCount: 12,
      categories: ['项目', '阅读'],
      tags: ['知识管理', '卡片笔记'],
      series: ['作品档案'],
      project: {
        status: 'paused',
        stack: ['Next.js', 'SQLite'],
        startedAt: '2026-05-20',
      },
    },
    {
      id: 'demo-page-about',
      title: '关于我',
      type: 'page',
      slug: 'about',
      status: 'published',
      visibility: 'public',
      publishedAt: '2026-06-06T09:00:00.000Z',
      createdAt: '2026-06-06T09:00:00.000Z',
      updatedAt: '2026-06-11T08:00:00.000Z',
      summary: '这里是 Starry Summer，一个记录写作、项目和日常的个人内容平台。',
      bodyMarkdown: [
        '## 你好',
        '',
        '这里会慢慢变成我的个人内容档案：文章记录完整想法，笔记收纳过程，日常保留现场，项目展示作品。',
        '',
        '这个站点只有我自己维护，但会尽量做成可以长期公网部署、可备份、可迁移的系统。',
      ].join('\n'),
      sourceType: 'original',
      sourceUrl: '',
      allowComments: false,
      pinned: false,
      featured: false,
      viewCount: 120,
      likeCount: 9,
      categories: ['关于'],
      tags: ['个人介绍', 'Starry Summer'],
      series: [],
    },
  ];
}

export function createDemoGuestbookEntries(): GuestbookEntryRecord[] {
  return [
    {
      id: 'demo-guestbook-1',
      authorName: 'Aster.H',
      body: '首页有内容之后整体感觉出来了，暗色氛围和内容卡片搭在一起更像一个个人档案馆。',
      status: 'approved',
      createdAt: '2026-06-11T11:20:00.000Z',
    },
    {
      id: 'demo-guestbook-2',
      authorName: 'Ada',
      body: '留言需要登录再提交，这个边界很好。公开展示和写入权限分开，后面公网部署会稳很多。',
      status: 'approved',
      createdAt: '2026-06-10T19:40:00.000Z',
    },
    {
      id: 'demo-guestbook-3',
      authorName: 'Summer Reader',
      body: '文章、笔记、项目、日常都有一点样例，浏览路径终于能串起来了。',
      status: 'approved',
      createdAt: '2026-06-09T23:16:00.000Z',
    },
    {
      id: 'demo-guestbook-4',
      authorName: 'GitHub Visitor',
      body: '这个站点如果继续做大，可以把专题和系列做成更强的导航入口。',
      status: 'approved',
      createdAt: '2026-06-08T13:08:00.000Z',
    },
  ];
}

export function createDemoComments(): CommentRecord[] {
  return [
    {
      id: 'demo-comment-1',
      targetType: 'post',
      targetId: 'demo-post-summer-archive',
      authorName: 'Ada',
      body: '这个名字的来源很适合放在第一篇，星空、夏夜和暖光一下子把站点气质立住了。',
      status: 'approved',
      createdAt: '2026-06-11T12:00:00.000Z',
    },
    {
      id: 'demo-comment-2',
      targetType: 'post',
      targetId: 'demo-post-docker-cloud',
      authorName: 'Ops Note',
      body: '部署文档里可以继续补一段备份恢复演练，云服务器上线前会安心很多。',
      status: 'approved',
      createdAt: '2026-06-10T16:05:00.000Z',
    },
    {
      id: 'demo-comment-3',
      targetType: 'project',
      targetId: 'demo-project-starry-summer',
      authorName: 'Builder',
      body: '项目页能展示技术栈、状态和仓库链接，作为作品档案已经够用了。',
      status: 'approved',
      createdAt: '2026-06-10T10:18:00.000Z',
    },
  ];
}
