import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { describe, expect, test } from 'vitest';

describe('leetcode archive page', () => {
  test('uses the repository dashboard for the public study archive', () => {
    const source = readFileSync(join(process.cwd(), 'src/app/leetcode/page.tsx'), 'utf8');
    const todayPageSource = readFileSync(join(process.cwd(), 'src/app/leetcode/today/page.tsx'), 'utf8');
    const snapshotSource = readFileSync(join(process.cwd(), 'src/app/leetcode/StudySnapshotHero.tsx'), 'utf8');
    const contributionSource = readFileSync(join(process.cwd(), 'src/app/leetcode/StudyContributionGraph.tsx'), 'utf8');
    const dailyCardsSource = readFileSync(join(process.cwd(), 'src/app/leetcode/StudyDailyCards.tsx'), 'utf8');
    const siteShellSource = readFileSync(join(process.cwd(), 'src/components/SiteShell.tsx'), 'utf8');
    const themeSyncSource = readFileSync(join(process.cwd(), 'src/components/ThemeSync.tsx'), 'utf8');

    expect(source).toContain('loadRepositoryStudyDashboard');
    expect(source).toContain('buildLeetCodeArchiveViewModel');
    expect(source).toContain('StudySnapshotHero');
    expect(source).not.toContain('StudyTodaySection');
    expect(source).not.toContain('<StudyTodaySection dashboard={dashboard} />');
    expect(todayPageSource).toContain('loadRepositoryStudyDashboard');
    expect(todayPageSource).toContain('StudyTodaySection');
    expect(todayPageSource).toContain('<StudyTodaySection dashboard={dashboard} />');
    expect(todayPageSource).toContain('href="/leetcode"');
    expect(source).toContain('<SiteShell>');
    expect(source).not.toContain('hideHeader');
    expect(siteShellSource).toContain('<StarrySkyCanvas className="site-shell__canvas" showFleet={false} />');
    expect(siteShellSource).toContain('<ThemeSync />');
    expect(themeSyncSource).toContain('document.documentElement.dataset.theme = nextTheme;');
    expect(themeSyncSource).toContain('window.sessionStorage.getItem(themeStorageKey)');
    expect(themeSyncSource).toContain('sessionTheme ?? getThemeCookie() ?? getThemeForTime()');
    expect(themeSyncSource).toContain('setThemeCookie(nextTheme);');
    expect(source).not.toContain('page-main__canvas');
    expect(snapshotSource).toContain('study-snapshot-hero');
    expect(snapshotSource).not.toContain('算法练习快照');
    expect(snapshotSource).not.toContain('<h1>');
    expect(snapshotSource).toContain('Hot100 / Review Log');
    expect(snapshotSource).toContain('今日题目、复习入口和提交轨迹，放在一页里继续推进。');
    expect(snapshotSource).not.toContain('Hot100 的公开学习记录，只展示进度、节奏和继续查看的入口。');
    expect(snapshotSource).not.toContain('仓库快照');
    expect(snapshotSource).not.toContain('lastSyncLabel');
    expect(snapshotSource).not.toContain('className="study-progress-link"');
    expect(snapshotSource).toContain('<span>进度</span>');
    expect(snapshotSource).toContain('StudyContributionGraph');
    expect(snapshotSource).toContain('heatmapDays={viewModel.heatmapDays}');
    expect(snapshotSource).toContain('StudyDailyCards');
    expect(snapshotSource).toContain('dashboard={dashboard}');
    expect(dailyCardsSource).toContain('今日推荐题目');
    expect(dailyCardsSource).toContain('今日复习题目');
    expect(dailyCardsSource).toContain('dashboard.todayFocus[0]');
    expect(dailyCardsSource).toContain('dashboard.reviewDue[0]');
    expect(dailyCardsSource).toContain('getLeetCodeProblemUrl');
    expect(dailyCardsSource).toContain('href="/leetcode/today"');
    expect(dailyCardsSource).not.toContain('href="#today-plan"');
    expect(dailyCardsSource).toContain('study-daily-card__surface');
    expect(dailyCardsSource).toContain('study-daily-card__problem-link');
    expect(dailyCardsSource).toContain('target="_blank"');
    expect(dailyCardsSource).toContain('rel="noreferrer"');
    expect(dailyCardsSource).toContain('study-daily-card-grid');
    expect(contributionSource).toContain('submissions in the last year');
    expect(contributionSource).toContain('study-contribution-grid');
    expect(contributionSource).toContain('study-contribution-months');
    expect(snapshotSource).toContain('href="#review-rhythm"');
    expect(snapshotSource).toContain('href="#categories"');
    expect(snapshotSource).toContain('className="study-snapshot-detail-row"');
    expect(snapshotSource).toContain('<div className="study-snapshot-detail-row" aria-label="学习明细入口">');
    expect(snapshotSource).toContain('href="/posts?tag=LeetCode"');
    expect(snapshotSource).toContain('dashboard.categories.slice(0, 6)');
    expect(snapshotSource).toContain('roundTrack.map');
    expect(source).not.toContain('PublicPageHeader');
    expect(source).not.toContain('StudyOverviewSection');
    expect(source).not.toContain('StudyNotesSection');
    expect(source).not.toContain('StudyRoundTrack');
    expect(source).not.toContain('StudyCategoryGrid');
    expect(source).not.toContain('StudyActivityPanel');
    expect(snapshotSource).toContain('href="#review-rhythm"');
    expect(snapshotSource).toContain('href="#categories"');
    expect(snapshotSource).toContain('study-round-link');
    expect(snapshotSource).toContain('study-category-chip');
    expect(snapshotSource).not.toContain('study-heatmap');
    expect(snapshotSource).not.toContain('study-note-grid');
    expect(snapshotSource).not.toContain('todayFocus');
    expect(snapshotSource).not.toContain('reviewDue');
    expect(source).not.toContain('function buildRoundTrack');
    expect(source).not.toContain('function buildCategoryAnchor');
    expect(source).not.toContain('function distributeDoneRounds');
    expect(source).not.toContain('function StudyTaskCard');
    expect(source).not.toContain('function ReviewTaskCard');
    expect(source).not.toContain('function StudyNoteCard');
    expect(source).not.toContain('getLeetCodeProblemUrl');
    expect(source).not.toContain('study-hero');
    expect(source).not.toContain('study-progress-orb');
    expect(source).not.toContain('study-command-grid');
    expect(source).not.toContain('study-task-board');
    expect(source).not.toContain('ContentCard');
    expect(source).not.toContain('recentReviews');
    expect(source).not.toContain('recentStudyNotes');
    expect(source).not.toContain('最近复盘');
    expect(source).not.toContain('loadPublicStudyDashboard');
    expect(source).not.toContain('API_BASE_URL');
  });
});
