import type { StudyProblem, StudyProblemListId } from './study';

type StudyProblemSeed = Omit<StudyProblem, 'rounds' | 'notes' | 'solutionViewed' | 'mustRepeat' | 'timeSpentSeconds' | 'updatedAt'>;

const STUDY_PROBLEM_SEEDS: StudyProblemSeed[] = [
  {number: 1, title: "两数之和", slug: "two-sum", difficulty: "简单", category: "哈希表", listIds: ["hot100", "top150"]},
  {number: 2, title: "两数相加", slug: "add-two-numbers", difficulty: "中等", category: "链表", listIds: ["hot100", "top150"]},
  {number: 3, title: "无重复字符的最长子串", slug: "longest-substring-without-repeating-characters", difficulty: "中等", category: "滑动窗口", listIds: ["hot100", "top150"]},
  {number: 4, title: "寻找两个正序数组的中位数", slug: "median-of-two-sorted-arrays", difficulty: "困难", category: "二分查找", listIds: ["hot100", "top150"]},
  {number: 5, title: "最长回文子串", slug: "longest-palindromic-substring", difficulty: "中等", category: "动态规划", listIds: ["hot100", "top150"]},
  {number: 11, title: "盛最多水的容器", slug: "container-with-most-water", difficulty: "中等", category: "双指针", listIds: ["hot100", "top150"]},
  {number: 15, title: "三数之和", slug: "3sum", difficulty: "中等", category: "双指针", listIds: ["hot100", "top150"]},
  {number: 17, title: "电话号码的字母组合", slug: "letter-combinations-of-a-phone-number", difficulty: "中等", category: "回溯", listIds: ["hot100", "top150"]},
  {number: 19, title: "删除链表的倒数第N个结点", slug: "remove-nth-node-from-end-of-list", difficulty: "中等", category: "链表", listIds: ["hot100", "top150"]},
  {number: 20, title: "有效的括号", slug: "valid-parentheses", difficulty: "简单", category: "栈", listIds: ["hot100", "top150"]},
  {number: 21, title: "合并两个有序链表", slug: "merge-two-sorted-lists", difficulty: "简单", category: "链表", listIds: ["hot100", "top150"]},
  {number: 22, title: "括号生成", slug: "generate-parentheses", difficulty: "中等", category: "回溯", listIds: ["hot100", "top150"]},
  {number: 23, title: "合并K个升序链表", slug: "merge-k-sorted-lists", difficulty: "困难", category: "链表", listIds: ["hot100", "top150"]},
  {number: 24, title: "两两交换链表中的节点", slug: "swap-nodes-in-pairs", difficulty: "中等", category: "链表", listIds: ["hot100"]},
  {number: 25, title: "K个一组翻转链表", slug: "reverse-nodes-in-k-group", difficulty: "困难", category: "链表", listIds: ["hot100", "top150"]},
  {number: 31, title: "下一个排列", slug: "next-permutation", difficulty: "中等", category: "数组", listIds: ["hot100"]},
  {number: 32, title: "最长有效括号", slug: "longest-valid-parentheses", difficulty: "困难", category: "栈", listIds: ["hot100"]},
  {number: 33, title: "搜索旋转排序数组", slug: "search-in-rotated-sorted-array", difficulty: "中等", category: "二分查找", listIds: ["hot100", "top150"]},
  {number: 34, title: "在排序数组中查找元素的第一个和最后一个位置", slug: "find-first-and-last-position-of-element-in-sorted-array", difficulty: "中等", category: "二分查找", listIds: ["hot100", "top150"]},
  {number: 39, title: "组合总和", slug: "combination-sum", difficulty: "中等", category: "回溯", listIds: ["hot100"]},
  {number: 41, title: "缺失的第一个正数", slug: "first-missing-positive", difficulty: "困难", category: "数组", listIds: ["hot100"]},
  {number: 42, title: "接雨水", slug: "trapping-rain-water", difficulty: "困难", category: "双指针", listIds: ["hot100", "top150"]},
  {number: 46, title: "全排列", slug: "permutations", difficulty: "中等", category: "回溯", listIds: ["hot100", "top150"]},
  {number: 48, title: "旋转图像", slug: "rotate-image", difficulty: "中等", category: "数组", listIds: ["hot100", "top150"]},
  {number: 49, title: "字母异位词分组", slug: "group-anagrams", difficulty: "中等", category: "哈希表", listIds: ["hot100", "top150"]},
  {number: 53, title: "最大子数组和", slug: "maximum-subarray", difficulty: "中等", category: "动态规划", listIds: ["hot100", "top150"]},
  {number: 55, title: "跳跃游戏", slug: "jump-game", difficulty: "中等", category: "贪心", listIds: ["hot100", "top150"]},
  {number: 56, title: "合并区间", slug: "merge-intervals", difficulty: "中等", category: "数组", listIds: ["hot100", "top150"]},
  {number: 62, title: "不同路径", slug: "unique-paths", difficulty: "中等", category: "动态规划", listIds: ["hot100"]},
  {number: 64, title: "最小路径和", slug: "minimum-path-sum", difficulty: "中等", category: "动态规划", listIds: ["hot100"]},
  {number: 70, title: "爬楼梯", slug: "climbing-stairs", difficulty: "简单", category: "动态规划", listIds: ["hot100", "top150"]},
  {number: 72, title: "编辑距离", slug: "edit-distance", difficulty: "中等", category: "动态规划", listIds: ["hot100"]},
  {number: 75, title: "颜色分类", slug: "sort-colors", difficulty: "中等", category: "双指针", listIds: ["hot100"]},
  {number: 76, title: "最小覆盖子串", slug: "minimum-window-substring", difficulty: "困难", category: "滑动窗口", listIds: ["hot100", "top150"]},
  {number: 78, title: "子集", slug: "subsets", difficulty: "中等", category: "回溯", listIds: ["hot100"]},
  {number: 79, title: "单词搜索", slug: "word-search", difficulty: "中等", category: "回溯", listIds: ["hot100"]},
  {number: 84, title: "柱状图中最大的矩形", slug: "largest-rectangle-in-histogram", difficulty: "困难", category: "栈", listIds: ["hot100"]},
  {number: 85, title: "最大矩形", slug: "maximal-rectangle", difficulty: "困难", category: "栈", listIds: ["hot100"]},
  {number: 94, title: "二叉树的中序遍历", slug: "binary-tree-inorder-traversal", difficulty: "简单", category: "二叉树", listIds: ["hot100"]},
  {number: 96, title: "不同的二叉搜索树", slug: "unique-binary-search-trees", difficulty: "中等", category: "动态规划", listIds: ["hot100"]},
  {number: 98, title: "验证二叉搜索树", slug: "validate-binary-search-tree", difficulty: "中等", category: "二叉树", listIds: ["hot100", "top150"]},
  {number: 101, title: "对称二叉树", slug: "symmetric-tree", difficulty: "简单", category: "二叉树", listIds: ["hot100", "top150"]},
  {number: 102, title: "二叉树的层序遍历", slug: "binary-tree-level-order-traversal", difficulty: "中等", category: "二叉树", listIds: ["hot100"]},
  {number: 104, title: "二叉树的最大深度", slug: "maximum-depth-of-binary-tree", difficulty: "简单", category: "二叉树", listIds: ["hot100", "top150"]},
  {number: 105, title: "从前序与中序遍历序列构造二叉树", slug: "construct-binary-tree-from-preorder-and-inorder-traversal", difficulty: "中等", category: "二叉树", listIds: ["hot100", "top150"]},
  {number: 114, title: "二叉树展开为链表", slug: "flatten-binary-tree-to-linked-list", difficulty: "中等", category: "二叉树", listIds: ["hot100", "top150"]},
  {number: 121, title: "买卖股票的最佳时机", slug: "best-time-to-buy-and-sell-stock", difficulty: "简单", category: "动态规划", listIds: ["hot100", "top150"]},
  {number: 124, title: "二叉树中的最大路径和", slug: "binary-tree-maximum-path-sum", difficulty: "困难", category: "二叉树", listIds: ["hot100", "top150"]},
  {number: 128, title: "最长连续序列", slug: "longest-consecutive-sequence", difficulty: "中等", category: "哈希表", listIds: ["hot100", "top150"]},
  {number: 136, title: "只出现一次的数字", slug: "single-number", difficulty: "简单", category: "位运算", listIds: ["hot100", "top150"]},
  {number: 139, title: "单词拆分", slug: "word-break", difficulty: "中等", category: "动态规划", listIds: ["hot100", "top150"]},
  {number: 141, title: "环形链表", slug: "linked-list-cycle", difficulty: "简单", category: "链表", listIds: ["hot100", "top150"]},
  {number: 142, title: "环形链表 II", slug: "linked-list-cycle-ii", difficulty: "中等", category: "链表", listIds: ["hot100"]},
  {number: 146, title: "LRU 缓存", slug: "lru-cache", difficulty: "中等", category: "设计", listIds: ["hot100", "top150"]},
  {number: 148, title: "排序链表", slug: "sort-list", difficulty: "中等", category: "链表", listIds: ["hot100", "top150"]},
  {number: 152, title: "乘积最大子数组", slug: "maximum-product-subarray", difficulty: "中等", category: "动态规划", listIds: ["hot100", "top150"]},
  {number: 155, title: "最小栈", slug: "min-stack", difficulty: "中等", category: "栈", listIds: ["hot100", "top150"]},
  {number: 160, title: "相交链表", slug: "intersection-of-two-linked-lists", difficulty: "简单", category: "链表", listIds: ["hot100"]},
  {number: 169, title: "多数元素", slug: "majority-element", difficulty: "简单", category: "数组", listIds: ["hot100", "top150"]},
  {number: 198, title: "打家劫舍", slug: "house-robber", difficulty: "中等", category: "动态规划", listIds: ["hot100", "top150"]},
  {number: 200, title: "岛屿数量", slug: "number-of-islands", difficulty: "中等", category: "图论", listIds: ["hot100", "top150"]},
  {number: 206, title: "反转链表", slug: "reverse-linked-list", difficulty: "简单", category: "链表", listIds: ["hot100", "top150"]},
  {number: 207, title: "课程表", slug: "course-schedule", difficulty: "中等", category: "图论", listIds: ["hot100", "top150"]},
  {number: 208, title: "实现 Trie (前缀树)", slug: "implement-trie-prefix-tree", difficulty: "中等", category: "设计", listIds: ["hot100", "top150"]},
  {number: 215, title: "数组中的第K个最大元素", slug: "kth-largest-element-in-an-array", difficulty: "中等", category: "堆", listIds: ["hot100", "top150"]},
  {number: 221, title: "最大正方形", slug: "maximal-square", difficulty: "中等", category: "动态规划", listIds: ["hot100", "top150"]},
  {number: 226, title: "翻转二叉树", slug: "invert-binary-tree", difficulty: "简单", category: "二叉树", listIds: ["hot100", "top150"]},
  {number: 234, title: "回文链表", slug: "palindrome-linked-list", difficulty: "简单", category: "链表", listIds: ["hot100"]},
  {number: 236, title: "二叉树的最近公共祖先", slug: "lowest-common-ancestor-of-a-binary-tree", difficulty: "中等", category: "二叉树", listIds: ["hot100", "top150"]},
  {number: 238, title: "除自身以外数组的乘积", slug: "product-of-array-except-self", difficulty: "中等", category: "数组", listIds: ["hot100", "top150"]},
  {number: 239, title: "滑动窗口最大值", slug: "sliding-window-maximum", difficulty: "困难", category: "栈", listIds: ["hot100"]},
  {number: 240, title: "搜索二维矩阵 II", slug: "search-a-2d-matrix-ii", difficulty: "中等", category: "二分查找", listIds: ["hot100"]},
  {number: 279, title: "完全平方数", slug: "perfect-squares", difficulty: "中等", category: "动态规划", listIds: ["hot100"]},
  {number: 283, title: "移动零", slug: "move-zeroes", difficulty: "简单", category: "双指针", listIds: ["hot100"]},
  {number: 287, title: "寻找重复数", slug: "find-the-duplicate-number", difficulty: "中等", category: "双指针", listIds: ["hot100"]},
  {number: 300, title: "最长递增子序列", slug: "longest-increasing-subsequence", difficulty: "中等", category: "动态规划", listIds: ["hot100", "top150"]},
  {number: 301, title: "删除无效的括号", slug: "remove-invalid-parentheses", difficulty: "困难", category: "回溯", listIds: ["hot100"]},
  {number: 309, title: "最佳买卖股票时机含冷冻期", slug: "best-time-to-buy-and-sell-stock-with-cooldown", difficulty: "中等", category: "动态规划", listIds: ["hot100"]},
  {number: 312, title: "戳气球", slug: "burst-balloons", difficulty: "困难", category: "动态规划", listIds: ["hot100"]},
  {number: 322, title: "零钱兑换", slug: "coin-change", difficulty: "中等", category: "动态规划", listIds: ["hot100", "top150"]},
  {number: 337, title: "打家劫舍 III", slug: "house-robber-iii", difficulty: "中等", category: "二叉树", listIds: ["hot100"]},
  {number: 338, title: "比特位计数", slug: "counting-bits", difficulty: "简单", category: "位运算", listIds: ["hot100"]},
  {number: 347, title: "前 K 个高频元素", slug: "top-k-frequent-elements", difficulty: "中等", category: "堆", listIds: ["hot100"]},
  {number: 394, title: "字符串解码", slug: "decode-string", difficulty: "中等", category: "栈", listIds: ["hot100"]},
  {number: 399, title: "除法求值", slug: "evaluate-division", difficulty: "中等", category: "图论", listIds: ["hot100", "top150"]},
  {number: 406, title: "根据身高重建队列", slug: "queue-reconstruction-by-height", difficulty: "中等", category: "贪心", listIds: ["hot100"]},
  {number: 416, title: "分割等和子集", slug: "partition-equal-subset-sum", difficulty: "中等", category: "动态规划", listIds: ["hot100"]},
  {number: 437, title: "路径总和 III", slug: "path-sum-iii", difficulty: "中等", category: "二叉树", listIds: ["hot100"]},
  {number: 438, title: "找到字符串中所有字母异位词", slug: "find-all-anagrams-in-a-string", difficulty: "中等", category: "滑动窗口", listIds: ["hot100"]},
  {number: 448, title: "找到所有数组中消失的数字", slug: "find-all-numbers-disappeared-in-an-array", difficulty: "简单", category: "数组", listIds: ["hot100"]},
  {number: 461, title: "汉明距离", slug: "hamming-distance", difficulty: "简单", category: "位运算", listIds: ["hot100"]},
  {number: 494, title: "目标和", slug: "target-sum", difficulty: "中等", category: "动态规划", listIds: ["hot100"]},
  {number: 538, title: "把二叉搜索树转换为累加树", slug: "convert-bst-to-greater-tree", difficulty: "中等", category: "二叉树", listIds: ["hot100"]},
  {number: 543, title: "二叉树的直径", slug: "diameter-of-binary-tree", difficulty: "简单", category: "二叉树", listIds: ["hot100"]},
  {number: 560, title: "和为 K 的子数组", slug: "subarray-sum-equals-k", difficulty: "中等", category: "哈希表", listIds: ["hot100"]},
  {number: 581, title: "最短无序连续子数组", slug: "shortest-unsorted-continuous-subarray", difficulty: "中等", category: "数组", listIds: ["hot100"]},
  {number: 617, title: "合并二叉树", slug: "merge-two-binary-trees", difficulty: "简单", category: "二叉树", listIds: ["hot100"]},
  {number: 621, title: "任务调度器", slug: "task-scheduler", difficulty: "中等", category: "贪心", listIds: ["hot100"]},
  {number: 647, title: "回文子串", slug: "palindromic-substrings", difficulty: "中等", category: "动态规划", listIds: ["hot100"]},
  {number: 739, title: "每日温度", slug: "daily-temperatures", difficulty: "中等", category: "栈", listIds: ["hot100"]},
  {number: 763, title: "划分字母区间", slug: "partition-labels", difficulty: "中等", category: "贪心", listIds: ["hot100"]},
  {number: 3, title: "数组中重复的数字", slug: "shu-zu-zhong-zhong-fu-de-shu-zi-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 4, title: "二维数组中的查找", slug: "er-wei-shu-zu-zhong-de-cha-zhao-lcof", difficulty: "中等", category: "其他", listIds: ["offer75"]},
  {number: 5, title: "替换空格", slug: "ti-huan-kong-ge-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 6, title: "从尾到头打印链表", slug: "cong-wei-dao-tou-da-yin-lian-biao-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 7, title: "重建二叉树", slug: "zhong-jian-er-cha-shu-lcof", difficulty: "中等", category: "其他", listIds: ["offer75"]},
  {number: 9, title: "用两个栈实现队列", slug: "yong-liang-ge-zhan-shi-xian-dui-lie-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 10, title: "斐波那契数列", slug: "fei-bo-na-qi-shu-lie-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 11, title: "旋转数组的最小数字", slug: "xuan-zhuan-shu-zu-de-zui-xiao-shu-zi-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 12, title: "矩阵中的路径", slug: "ju-zhen-zhong-de-lu-jing-lcof", difficulty: "中等", category: "其他", listIds: ["offer75"]},
  {number: 13, title: "机器人的运动范围", slug: "ji-qi-ren-de-yun-dong-fan-wei-lcof", difficulty: "中等", category: "其他", listIds: ["offer75"]},
  {number: 14, title: "剪绳子", slug: "jian-sheng-zi-lcof", difficulty: "中等", category: "其他", listIds: ["offer75"]},
  {number: 15, title: "二进制中1的个数", slug: "er-jin-zhi-zhong-1de-ge-shu-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 16, title: "数值的整数次方", slug: "shu-zhi-de-zheng-shu-ci-fang-lcof", difficulty: "中等", category: "其他", listIds: ["offer75"]},
  {number: 17, title: "打印从1到最大的n位数", slug: "da-yin-cong-1dao-zui-da-de-nwei-shu-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 18, title: "删除链表的节点", slug: "shan-chu-lian-biao-de-jie-dian-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 21, title: "调整数组顺序使奇数位于偶数前面", slug: "diao-zheng-shu-zu-shun-xu-shi-qi-shu-wei-yu-ou-shu-qian-mian-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 22, title: "链表中倒数第k个节点", slug: "lian-biao-zhong-dao-shu-di-kge-jie-dian-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 24, title: "反转链表", slug: "fan-zhuan-lian-biao-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 25, title: "合并两个排序的链表", slug: "he-bing-liang-ge-pai-xu-de-lian-biao-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 26, title: "树的子结构", slug: "shu-de-zi-jie-gou-lcof", difficulty: "中等", category: "其他", listIds: ["offer75"]},
  {number: 27, title: "二叉树的镜像", slug: "er-cha-shu-de-jing-xiang-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 28, title: "对称的二叉树", slug: "dui-cheng-de-er-cha-shu-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 29, title: "顺时针打印矩阵", slug: "shun-shi-zhen-da-yin-ju-zhen-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 30, title: "包含min函数的栈", slug: "bao-han-minhan-shu-de-zhan-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 31, title: "栈的压入、弹出序列", slug: "zhan-de-ya-ru-dan-chu-xu-lie-lcof", difficulty: "中等", category: "其他", listIds: ["offer75"]},
  {number: 32, title: "从上到下打印二叉树", slug: "cong-shang-dao-xia-da-yin-er-cha-shu-lcof", difficulty: "中等", category: "其他", listIds: ["offer75"]},
  {number: 33, title: "二叉搜索树的后序遍历序列", slug: "er-cha-sou-suo-shu-de-hou-xu-bian-li-xu-lie-lcof", difficulty: "中等", category: "其他", listIds: ["offer75"]},
  {number: 34, title: "二叉树中和为某一值的路径", slug: "er-cha-shu-zhong-he-wei-mou-yi-zhi-de-lu-jing-lcof", difficulty: "中等", category: "其他", listIds: ["offer75"]},
  {number: 35, title: "复杂链表的复制", slug: "fu-za-lian-biao-de-fu-zhi-lcof", difficulty: "中等", category: "其他", listIds: ["offer75"]},
  {number: 36, title: "二叉搜索树与双向链表", slug: "er-cha-sou-suo-shu-yu-shuang-xiang-lian-biao-lcof", difficulty: "中等", category: "其他", listIds: ["offer75"]},
  {number: 37, title: "序列化二叉树", slug: "xu-lie-hua-er-cha-shu-lcof", difficulty: "困难", category: "其他", listIds: ["offer75"]},
  {number: 38, title: "字符串的排列", slug: "zi-fu-chuan-de-pai-lie-lcof", difficulty: "中等", category: "其他", listIds: ["offer75"]},
  {number: 39, title: "数组中出现次数超过一半的数字", slug: "shu-zu-zhong-chu-xian-ci-shu-chao-guo-yi-ban-de-shu-zi-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 40, title: "最小的k个数", slug: "zui-xiao-de-kge-shu-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 42, title: "连续子数组的最大和", slug: "lian-xu-zi-shu-zu-de-zui-da-he-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 46, title: "把数字翻译成字符串", slug: "ba-shu-zi-fan-yi-cheng-zi-fu-chuan-lcof", difficulty: "中等", category: "其他", listIds: ["offer75"]},
  {number: 47, title: "礼物的最大价值", slug: "li-wu-de-zui-da-jie-zhi-lcof", difficulty: "中等", category: "其他", listIds: ["offer75"]},
  {number: 48, title: "最长不含重复字符的子字符串", slug: "zui-chang-bu-han-zhong-fu-zi-fu-de-zi-zi-fu-chuan-lcof", difficulty: "中等", category: "其他", listIds: ["offer75"]},
  {number: 50, title: "第一个只出现一次的字符", slug: "di-yi-ge-zhi-chu-xian-yi-ci-de-zi-fu-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 52, title: "两个链表的第一个公共节点", slug: "liang-ge-lian-biao-de-di-yi-ge-gong-gong-jie-dian-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 53, title: "在排序数组中查找数字", slug: "zai-pai-xu-shu-zu-zhong-cha-zhao-shu-zi-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 54, title: "二叉搜索树的第k大节点", slug: "er-cha-sou-suo-shu-de-di-kda-jie-dian-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 55, title: "二叉树的深度", slug: "er-cha-shu-de-shen-du-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 56, title: "数组中数字出现的次数", slug: "shu-zu-zhong-shu-zi-chu-xian-de-ci-shu-lcof", difficulty: "中等", category: "其他", listIds: ["offer75"]},
  {number: 57, title: "和为s的两个数字", slug: "he-wei-sde-liang-ge-shu-zi-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 58, title: "翻转单词顺序", slug: "fan-zhuan-dan-ci-shun-xu-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 59, title: "滑动窗口的最大值", slug: "hua-dong-chuang-kou-de-zui-da-zhi-lcof", difficulty: "困难", category: "其他", listIds: ["offer75"]},
  {number: 60, title: "n个骰子的点数", slug: "nge-tou-zi-de-dian-shu-lcof", difficulty: "中等", category: "其他", listIds: ["offer75"]},
  {number: 61, title: "扑克牌中的顺子", slug: "bu-ke-pai-zhong-de-shun-zi-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 63, title: "股票的最大利润", slug: "gu-piao-de-zui-da-li-run-lcof", difficulty: "中等", category: "其他", listIds: ["offer75"]},
  {number: 64, title: "求1+2+…+n", slug: "qiu-12n-lcof", difficulty: "中等", category: "其他", listIds: ["offer75"]},
  {number: 65, title: "不用加减乘除做加法", slug: "bu-yong-jia-jian-cheng-chu-zuo-jia-fa-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 66, title: "构建乘积数组", slug: "gou-jian-cheng-ji-shu-zu-lcof", difficulty: "中等", category: "其他", listIds: ["offer75"]},
  {number: 68, title: "二叉搜索树的最近公共祖先", slug: "er-cha-sou-suo-shu-de-zui-jin-gong-gong-zu-xian-lcof", difficulty: "简单", category: "其他", listIds: ["offer75"]},
  {number: 6, title: "N 字形变换", slug: "zigzag-conversion", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 7, title: "整数反转", slug: "reverse-integer", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 8, title: "字符串转换整数 (atoi)", slug: "string-to-integer-atoi", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 9, title: "回文数", slug: "palindrome-number", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 13, title: "罗马数字转整数", slug: "roman-to-integer", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 14, title: "最长公共前缀", slug: "longest-common-prefix", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 26, title: "删除有序数组中的重复项", slug: "remove-duplicates-from-sorted-array", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 27, title: "移除元素", slug: "remove-element", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 28, title: "找出字符串中第一个匹配项的下标", slug: "find-the-index-of-the-first-occurrence-in-a-string", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 30, title: "串联所有单词的子串", slug: "substring-with-concatenation-of-all-words", difficulty: "困难", category: "其他", listIds: ["top150"]},
  {number: 35, title: "搜索插入位置", slug: "search-insert-position", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 36, title: "有效的数独", slug: "valid-sudoku", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 45, title: "跳跃游戏 II", slug: "jump-game-ii", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 54, title: "螺旋矩阵", slug: "spiral-matrix", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 57, title: "插入区间", slug: "insert-interval", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 58, title: "最后一个单词的长度", slug: "length-of-last-word", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 61, title: "旋转链表", slug: "rotate-list", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 67, title: "二进制求和", slug: "add-binary", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 68, title: "文本左右对齐", slug: "text-justification", difficulty: "困难", category: "其他", listIds: ["top150"]},
  {number: 69, title: "x 的平方根", slug: "sqrtx", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 71, title: "简化路径", slug: "simplify-path", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 73, title: "矩阵置零", slug: "set-matrix-zeroes", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 74, title: "搜索二维矩阵", slug: "search-a-2d-matrix", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 77, title: "组合", slug: "combinations", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 80, title: "删除有序数组中的重复项 II", slug: "remove-duplicates-from-sorted-array-ii", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 82, title: "删除排序链表中的重复元素 II", slug: "remove-duplicates-from-sorted-list-ii", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 86, title: "分隔链表", slug: "partition-list", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 88, title: "合并两个有序数组", slug: "merge-sorted-array", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 92, title: "反转链表 II", slug: "reverse-linked-list-ii", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 97, title: "交错字符串", slug: "interleaving-string", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 100, title: "相同的树", slug: "same-tree", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 106, title: "从中序与后序遍历序列构造二叉树", slug: "construct-binary-tree-from-inorder-and-postorder-traversal", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 108, title: "将有序数组转换为二叉搜索树", slug: "convert-sorted-array-to-binary-search-tree", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 112, title: "路径总和", slug: "path-sum", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 117, title: "填充每个节点的下一个右侧节点指针 II", slug: "populating-next-right-pointers-in-each-node-ii", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 122, title: "买卖股票的最佳时机 II", slug: "best-time-to-buy-and-sell-stock-ii", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 125, title: "验证回文串", slug: "valid-palindrome", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 127, title: "单词接龙", slug: "word-ladder", difficulty: "困难", category: "其他", listIds: ["top150"]},
  {number: 129, title: "求根节点到叶节点数字之和", slug: "sum-root-to-leaf-numbers", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 130, title: "被围绕的区域", slug: "surrounded-regions", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 131, title: "分割回文串", slug: "palindrome-partitioning", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 133, title: "克隆图", slug: "clone-graph", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 134, title: "加油站", slug: "gas-station", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 135, title: "分发糖果", slug: "candy", difficulty: "困难", category: "其他", listIds: ["top150"]},
  {number: 137, title: "只出现一次的数字 II", slug: "single-number-ii", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 138, title: "随机链表的复制", slug: "copy-list-with-random-pointer", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 150, title: "逆波兰表达式求值", slug: "evaluate-reverse-polish-notation", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 151, title: "反转字符串中的单词", slug: "reverse-words-in-a-string", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 153, title: "寻找旋转排序数组中的最小值", slug: "find-minimum-in-rotated-sorted-array", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 162, title: "寻找峰值", slug: "find-peak-element", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 167, title: "两数之和 II", slug: "two-sum-ii-input-array-is-sorted", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 172, title: "阶乘后的零", slug: "factorial-trailing-zeroes", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 189, title: "轮转数组", slug: "rotate-array", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 190, title: "颠倒二进制位", slug: "reverse-bits", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 191, title: "位1的个数", slug: "number-of-1-bits", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 199, title: "二叉树的右视图", slug: "binary-tree-right-side-view", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 201, title: "数字范围按位与", slug: "bitwise-and-of-numbers-range", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 202, title: "快乐数", slug: "happy-number", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 205, title: "同构字符串", slug: "isomorphic-strings", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 209, title: "长度最小的子数组", slug: "minimum-size-subarray-sum", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 210, title: "课程表 II", slug: "course-schedule-ii", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 211, title: "添加与搜索单词", slug: "design-add-and-search-words-data-structure", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 212, title: "单词搜索 II", slug: "word-search-ii", difficulty: "困难", category: "其他", listIds: ["top150"]},
  {number: 219, title: "存在重复元素 II", slug: "contains-duplicate-ii", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 222, title: "完全二叉树的节点个数", slug: "count-complete-tree-nodes", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 224, title: "基本计算器", slug: "basic-calculator", difficulty: "困难", category: "其他", listIds: ["top150"]},
  {number: 228, title: "汇总区间", slug: "summary-ranges", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 230, title: "二叉搜索树中第K小的元素", slug: "kth-smallest-element-in-a-bst", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 242, title: "有效的字母异位词", slug: "valid-anagram", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 274, title: "H 指数", slug: "h-index", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 289, title: "生命游戏", slug: "game-of-life", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 290, title: "单词规律", slug: "word-pattern", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 380, title: "O(1) 时间插入、删除和获取随机元素", slug: "insert-delete-getrandom-o1", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 383, title: "赎金信", slug: "ransom-note", difficulty: "简单", category: "其他", listIds: ["top150"]},
  {number: 427, title: "建立四叉树", slug: "construct-quad-tree", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 433, title: "最小基因变化", slug: "minimum-genetic-mutation", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 452, title: "用最少数量的箭引爆气球", slug: "minimum-number-of-arrows-to-burst-balloons", difficulty: "中等", category: "其他", listIds: ["top150"]},
  {number: 530, title: "二叉搜索树的最小绝对差", slug: "minimum-absolute-difference-in-bst", difficulty: "简单", category: "其他", listIds: ["top150"]},
];

export const STUDY_PROBLEM_LIST_COUNTS: Record<StudyProblemListId, number> = {
  hot100: 101,
  offer75: 54,
  top150: 132,
};

export const STUDY_PROBLEMS: StudyProblem[] = STUDY_PROBLEM_SEEDS.map((problem) => ({
  ...problem,
  rounds: [],
  notes: '',
  solutionViewed: false,
  mustRepeat: false,
  timeSpentSeconds: [],
  updatedAt: '',
}));
