#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

env_file="${1:-.env}"

if [[ ! -f "$env_file" ]]; then
  echo "Environment file not found: $env_file"
  echo "Usage: npm run ops:doctor -- .env"
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$env_file"
set +a

errors=0

fail() {
  echo "[error] $1"
  errors=$((errors + 1))
}

is_unset_or_placeholder() {
  local value="${1:-}"

  [[ -z "$value" || "$value" == replace-* || "$value" == change-* ]]
}

is_example_com_hostname() {
  local value="${1:-}"

  [[ "$value" == "example.com" || "$value" == *.example.com ]]
}

case "${DOMAIN:-}" in
  "" | localhost | 127.0.0.1)
    fail "DOMAIN must be your public domain, not localhost."
    ;;
  *://* | */* | *:*)
    fail "DOMAIN must be a hostname without a scheme or path."
    ;;
esac

if is_example_com_hostname "${DOMAIN:-}"; then
  fail "DOMAIN must not use an example.com placeholder."
fi

if [[ "${PUBLIC_SITE_URL:-}" != https://* ]]; then
  fail "PUBLIC_SITE_URL must start with https:// for production."
fi

public_site_host="$(
  node -e "try { process.stdout.write(new URL(process.argv[1]).hostname) } catch { process.exit(1) }" "${PUBLIC_SITE_URL:-}" 2>/dev/null || true
)"

if [[ -z "$public_site_host" ]]; then
  fail "PUBLIC_SITE_URL must be a valid URL."
fi

if is_example_com_hostname "$public_site_host"; then
  fail "PUBLIC_SITE_URL must not use an example.com placeholder."
fi

if [[ -n "${DOMAIN:-}" && -n "$public_site_host" && "$public_site_host" != "$DOMAIN" ]]; then
  fail "PUBLIC_SITE_URL host must match DOMAIN."
fi

if [[ "${ACME_EMAIL:-}" != *@* ]]; then
  fail "ACME_EMAIL must be a valid email for HTTPS certificates."
elif [[ "${ACME_EMAIL:-}" == *@example.com ]]; then
  fail "ACME_EMAIL must not use an example.com placeholder."
fi

if is_unset_or_placeholder "${ADMIN_EMAIL:-}"; then
  fail "ADMIN_EMAIL must be set to the owner login account."
elif [[ "${ADMIN_EMAIL:-}" == *@example.com ]]; then
  fail "ADMIN_EMAIL must not use an example.com placeholder."
fi

if is_unset_or_placeholder "${ADMIN_PASSWORD_HASH:-}"; then
  fail "ADMIN_PASSWORD_HASH is still a placeholder."
elif [[ "${ADMIN_PASSWORD_HASH:-}" != scrypt:* ]]; then
  fail "ADMIN_PASSWORD_HASH must be generated by npm run auth:hash-password."
fi

session_secret="${SESSION_SECRET:-}"

if [[ ${#session_secret} -lt 32 ]] || is_unset_or_placeholder "$session_secret"; then
  fail "SESSION_SECRET must be at least 32 characters and not a placeholder."
fi

interaction_hash_secret="${INTERACTION_HASH_SECRET:-}"

if [[ ${#interaction_hash_secret} -lt 32 ]] || is_unset_or_placeholder "$interaction_hash_secret"; then
  fail "INTERACTION_HASH_SECRET must be at least 32 characters and not a placeholder."
fi

if [[ -n "$session_secret" && "$session_secret" == "$interaction_hash_secret" ]]; then
  fail "INTERACTION_HASH_SECRET must be different from SESSION_SECRET."
fi

if is_unset_or_placeholder "${GITHUB_CLIENT_ID:-}"; then
  fail "GITHUB_CLIENT_ID is required for guestbook GitHub login."
fi

if is_unset_or_placeholder "${GITHUB_CLIENT_SECRET:-}"; then
  fail "GITHUB_CLIENT_SECRET is required for guestbook GitHub login."
fi

expected_github_callback_url="${PUBLIC_SITE_URL%/}/api/auth/github/callback"

if is_unset_or_placeholder "${GITHUB_CALLBACK_URL:-}"; then
  fail "GITHUB_CALLBACK_URL must be set to the GitHub OAuth callback URL."
elif [[ "${GITHUB_CALLBACK_URL:-}" != "$expected_github_callback_url" ]]; then
  fail "GITHUB_CALLBACK_URL must equal PUBLIC_SITE_URL plus /api/auth/github/callback."
fi

if [[ "$errors" -gt 0 ]]; then
  echo "Deployment environment has $errors issue(s)."
  exit 1
fi

echo "Deployment environment looks ready."
