#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

env_file="${1:-.env}"

if [[ ! -f "$env_file" ]]; then
  echo "Environment file not found: $env_file"
  echo "Usage: npm run ops:doctor -- .env"
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$env_file"
set +a

errors=0

fail() {
  echo "[error] $1"
  errors=$((errors + 1))
}

is_unset_or_placeholder() {
  local value="${1:-}"

  [[ -z "$value" || "$value" == replace-* || "$value" == change-* ]]
}

case "${DOMAIN:-}" in
  "" | localhost | 127.0.0.1)
    fail "DOMAIN must be your public domain, not localhost."
    ;;
esac

if [[ "${PUBLIC_SITE_URL:-}" != https://* ]]; then
  fail "PUBLIC_SITE_URL must start with https:// for production."
fi

public_site_host="$(
  node -e "try { process.stdout.write(new URL(process.argv[1]).hostname) } catch { process.exit(1) }" "${PUBLIC_SITE_URL:-}" 2>/dev/null || true
)"

if [[ -n "${DOMAIN:-}" && -n "$public_site_host" && "$public_site_host" != "$DOMAIN" ]]; then
  fail "PUBLIC_SITE_URL host must match DOMAIN."
fi

if [[ "${ACME_EMAIL:-}" != *@* ]]; then
  fail "ACME_EMAIL must be a valid email for HTTPS certificates."
fi

if [[ "${ADMIN_EMAIL:-}" != *@* ]]; then
  fail "ADMIN_EMAIL must be a valid owner login email."
fi

if is_unset_or_placeholder "${ADMIN_PASSWORD_HASH:-}"; then
  fail "ADMIN_PASSWORD_HASH is still a placeholder."
elif [[ "${ADMIN_PASSWORD_HASH:-}" != scrypt:* ]]; then
  fail "ADMIN_PASSWORD_HASH must be generated by npm run auth:hash-password."
fi

session_secret="${SESSION_SECRET:-}"

if [[ ${#session_secret} -lt 32 ]] || is_unset_or_placeholder "$session_secret"; then
  fail "SESSION_SECRET must be at least 32 characters and not a placeholder."
fi

interaction_hash_secret="${INTERACTION_HASH_SECRET:-}"

if [[ ${#interaction_hash_secret} -lt 32 ]] || is_unset_or_placeholder "$interaction_hash_secret"; then
  fail "INTERACTION_HASH_SECRET must be at least 32 characters and not a placeholder."
fi

case "${POSTGRES_PASSWORD:-}" in
  "" | starry | postgres | password | change-me-before-production)
    fail "POSTGRES_PASSWORD must not use a default or weak value."
    ;;
esac

if [[ -z "${DATABASE_URL:-}" ]]; then
  fail "DATABASE_URL must be set for the API database connection."
elif [[ "${DATABASE_URL}" == *":starry@"* ]]; then
  fail "DATABASE_URL must not use the default starry database password."
elif [[ "${DATABASE_URL}" == *":postgres@"* || "${DATABASE_URL}" == *":password@"* ]]; then
  fail "DATABASE_URL must not use a default database password."
fi

database_url_password="$(
  node -e "try { process.stdout.write(decodeURIComponent(new URL(process.argv[1]).password)) } catch { process.exit(1) }" "${DATABASE_URL:-}" 2>/dev/null || true
)"

if [[ -n "${DATABASE_URL:-}" && -z "$database_url_password" ]]; then
  fail "DATABASE_URL must include the PostgreSQL password."
elif [[ -n "${POSTGRES_PASSWORD:-}" && -n "$database_url_password" && "$database_url_password" != "${POSTGRES_PASSWORD:-}" ]]; then
  fail "DATABASE_URL password must match POSTGRES_PASSWORD."
fi

if [[ "${CONTENT_REPOSITORY_DRIVER:-}" != "postgres" ]]; then
  fail "CONTENT_REPOSITORY_DRIVER must be postgres for production."
fi

case "${STORAGE_DRIVER:-local}" in
  local | s3)
    ;;
  *)
    fail "STORAGE_DRIVER must be either local or s3."
    ;;
esac

if [[ "${STORAGE_DRIVER:-local}" == "local" ]]; then
  local_upload_public_url="${LOCAL_UPLOAD_PUBLIC_URL:-/uploads}"

  if [[ "$local_upload_public_url" != /* || "$local_upload_public_url" == //* ]]; then
    fail "LOCAL_UPLOAD_PUBLIC_URL must be a root-relative path when STORAGE_DRIVER=local."
  fi
fi

if [[ "${STORAGE_DRIVER:-local}" == "s3" ]]; then
  if [[ "${S3_PUBLIC_BASE_URL:-}" != https://* ]]; then
    fail "S3_PUBLIC_BASE_URL must start with https:// when STORAGE_DRIVER=s3."
  fi

  case "${S3_ACCESS_KEY:-}" in
    "" | minioadmin | access-key | change-me-before-production)
      fail "S3_ACCESS_KEY must not use a default or placeholder value when STORAGE_DRIVER=s3."
      ;;
  esac

  case "${S3_SECRET_KEY:-}" in
    "" | minioadmin | secret-key | change-me-before-production)
      fail "S3_SECRET_KEY must not use a default or placeholder value when STORAGE_DRIVER=s3."
      ;;
  esac
fi

if [[ "$errors" -gt 0 ]]; then
  echo "Deployment environment has $errors issue(s)."
  exit 1
fi

echo "Deployment environment looks ready."
