import type { SiteContentItem } from './content-types';

export const seedContent: SiteContentItem[] = [
  {
    id: 'intro-post',
    title: 'Why Starry Summer exists',
    type: 'post',
    status: 'published',
    visibility: 'public',
    publishedAt: '2026-06-14',
    updatedAt: '2026-06-14',
    summary: 'A quiet personal content platform for long-term public writing, notes, moments, and projects.',
    bodyMarkdown: [
      '## A small archive that can last',
      '',
      'Starry Summer is meant to keep writing portable and visible without locking long-term content inside a database.',
      '',
      'The public site reads repository files first. Admin publishing writes content back as repository changes. Dynamic interaction can live in small hosted services when the static files are not enough.',
    ].join('\n'),
    slug: 'why-starry-summer',
    coverImageUrl: '/images/starry-summer-night.png',
    coverAltText: 'A moonlit summer night under a starry sky',
    featured: true,
    pinned: true,
    categories: ['Writing', 'Platform'],
    tags: ['Starry Summer', 'Archive', 'Repository'],
    series: ['Platform Journal'],
    viewCount: 128,
    likeCount: 18,
  },
  {
    id: 'note-markdown',
    title: 'Markdown keeps content portable',
    type: 'note',
    status: 'published',
    visibility: 'public',
    publishedAt: '2026-06-09',
    summary: 'Markdown and JSON files make content easy to inspect, review, back up, and move.',
    bodyMarkdown: [
      '## Content should be easy to carry',
      '',
      'Markdown is the escape hatch. It is simple enough to read directly and stable enough to keep for years.',
      '',
      'Repository files also make review and backup boring in the best way: every important change can be inspected as a normal diff.',
    ].join('\n'),
    slug: 'markdown-ownership',
    categories: ['Notes', 'Writing'],
    tags: ['Markdown', 'Repository'],
    series: ['Platform Journal'],
    viewCount: 76,
    likeCount: 9,
  },
  {
    id: 'project-starry',
    title: 'Starry Summer',
    type: 'project',
    status: 'published',
    visibility: 'public',
    publishedAt: '2026-06-08',
    summary: 'A personal content platform for posts, notes, moments, projects, and repository-backed publishing.',
    bodyMarkdown: [
      '## Platform direction',
      '',
      'Starry Summer favors a static-friendly architecture: Next.js for the public and admin surfaces, repository JSON for durable content, Markdown for writing, and hosted workers for dynamic edges.',
    ].join('\n'),
    slug: 'starry-summer',
    coverImageUrl: '/images/default-post-cover.png',
    coverAltText: 'Starry Summer project cover',
    featured: true,
    categories: ['Projects', 'Platform'],
    tags: ['Next.js', 'Markdown', 'Repository'],
    series: ['Platform Journal'],
    project: {
      status: 'active',
      stack: ['Next.js', 'Markdown', 'Repository JSON', 'Vercel', 'GitHub API'],
      startedAt: '2026-06-10',
    },
    viewCount: 214,
    likeCount: 31,
  },
  {
    id: 'moment-first',
    title: 'The foundation is simpler now',
    type: 'moment',
    status: 'published',
    visibility: 'public',
    publishedAt: '2026-06-07',
    summary: 'The platform starts from public pages, repository content, and a small admin publishing surface.',
    bodyMarkdown: 'Today the boundary is clearer: public pages, repository files, admin publishing, and optional hosted interaction services each have their own place.',
    slug: 'first-foundation',
    categories: ['Daily'],
    tags: ['Daily', 'Architecture'],
    viewCount: 52,
    likeCount: 7,
  },
];
