import type { SiteContentItem } from './content-types';

export const seedContent: SiteContentItem[] = [
  {
    id: 'intro-post',
    title: '把个人站做成长期内容系统',
    type: 'post',
    status: 'published',
    visibility: 'public',
    publishedAt: '2026-06-10',
    updatedAt: '2026-06-11',
    summary: '从博客、笔记、日常和项目四条线开始，把写作和作品沉淀成一个可部署的平台。',
    bodyMarkdown: [
      '## 为什么要做成系统',
      '',
      '个人博客不只是几篇文章的展示页。它应该能持续收纳文章、笔记、日常和项目，让内容随着时间自然生长。',
      '',
      '### 四条内容线',
      '',
      '- 文章负责沉淀完整思考',
      '- 笔记负责记录过程和片段',
      '- 项目负责展示作品和技术路线',
      '',
      '```ts',
      'const contentLines = ["文章", "笔记", "日常", "项目"];',
      '```',
      '',
      '## 下一步',
      '',
      '这个站点会优先保证内容所有权、部署稳定性和后台写作效率。',
    ].join('\n'),
    slug: 'personal-content-platform',
    coverImageUrl: '/images/default-post-cover.png',
    coverAltText: '把个人站做成长期内容系统 默认文章封面',
    featured: true,
    categories: ['Writing', 'Platform'],
    tags: ['Platform', 'Writing', 'System'],
    series: ['Platform Journal'],
    viewCount: 128,
    likeCount: 18,
  },
  {
    id: 'note-markdown',
    title: 'Markdown 是内容的逃生门',
    type: 'note',
    status: 'published',
    visibility: 'public',
    publishedAt: '2026-06-09',
    summary: '数据库负责运行时体验，Markdown 导入导出负责长期所有权。',
    bodyMarkdown: [
      '## 内容要能带走',
      '',
      '数据库适合检索、权限和互动，但长期内容不能只锁在数据库里。',
      '',
      'Markdown 是内容的逃生门：它足够朴素，也足够稳定。后续导入导出会围绕 frontmatter 和正文双向转换展开。',
    ].join('\n'),
    slug: 'markdown-ownership',
    categories: ['Notes', 'Writing'],
    tags: ['Markdown', 'Archive'],
    series: ['Platform Journal'],
    viewCount: 76,
    likeCount: 9,
  },
  {
    id: 'project-starry',
    title: 'Starry Summer',
    type: 'project',
    status: 'published',
    visibility: 'public',
    publishedAt: '2026-06-08',
    summary: '个人内容平台：文章、笔记、日常、项目、评论、后台管理和云服务器部署。',
    bodyMarkdown: [
      '## 平台目标',
      '',
      'Starry Summer 面向单人长期使用：公网展示内容，后台维护文章、笔记、项目和互动。',
      '',
      '当前技术栈选择 Next.js、NestJS、PostgreSQL 和 Docker Compose，方便先在一台云服务器上稳定运行，再按规模逐步拆分。',
    ].join('\n'),
    slug: 'starry-summer',
    coverImageUrl: '/images/default-post-cover.png',
    coverAltText: 'Starry Summer 默认文章封面',
    featured: true,
    categories: ['Projects', 'Platform'],
    tags: ['Next.js', 'NestJS', 'PostgreSQL'],
    series: ['Platform Journal'],
    project: {
      status: 'active',
      stack: ['Next.js', 'NestJS', 'PostgreSQL', 'Redis', 'Docker'],
      startedAt: '2026-06-10',
    },
    viewCount: 214,
    likeCount: 31,
  },
  {
    id: 'moment-first',
    title: '今天先把地基打好',
    type: 'moment',
    status: 'published',
    visibility: 'public',
    publishedAt: '2026-06-07',
    summary: '一个能长期长大的个人平台，第一天最重要的是边界清楚。',
    bodyMarkdown: '今天先把可部署的边界打清楚：公开页面、后台入口、API、数据库和部署流程各自独立，后面扩展才不会乱。',
    slug: 'first-foundation',
    categories: ['Daily'],
    tags: ['Daily'],
    viewCount: 44,
    likeCount: 6,
  },
  {
    id: 'about-page',
    title: 'About Starry Summer',
    type: 'page',
    status: 'published',
    visibility: 'public',
    publishedAt: '2026-06-06',
    summary: '一个用于沉淀写作、项目和日常记录的个人内容平台。',
    bodyMarkdown: 'Starry Summer 是一个个人内容系统，用来记录文章、笔记、日常和项目，也保留评论、导出和后台管理能力。',
    slug: 'about',
    categories: ['Site'],
    tags: ['About'],
    viewCount: 31,
    likeCount: 2,
  },
];
