import type { SiteContentItem } from './content-types';

export const seedContent: SiteContentItem[] = [
  {
    id: 'intro-post',
    title: 'Why Starry Summer exists',
    type: 'post',
    status: 'published',
    visibility: 'public',
    publishedAt: '2026-06-14',
    updatedAt: '2026-06-14',
    summary: 'A quiet personal content platform for long-term public writing, notes, moments, and projects.',
    bodyMarkdown: [
      '## A small archive that can last',
      '',
      'Starry Summer is meant to keep writing portable and visible without locking long-term content inside a database.',
      '',
      'The public site reads repository files first. Admin publishing writes content back as repository changes. Dynamic interaction can live in small hosted services when the static files are not enough.',
    ].join('\n'),
    slug: 'why-starry-summer',
    coverImageUrl: '/images/starry-summer-night.png',
    coverAltText: 'A moonlit summer night under a starry sky',
    featured: true,
    pinned: true,
    categories: ['Writing', 'Platform'],
    tags: ['Starry Summer', 'Archive', 'Repository'],
    series: ['Platform Journal'],
    viewCount: 128,
    likeCount: 18,
  },
  {
    id: 'note-markdown',
    title: 'Markdown keeps content portable',
    type: 'note',
    status: 'published',
    visibility: 'public',
    publishedAt: '2026-06-09',
    summary: 'Markdown and JSON files make content easy to inspect, review, back up, and move.',
    bodyMarkdown: [
      '## Content should be easy to carry',
      '',
      'Markdown is the escape hatch. It is simple enough to read directly and stable enough to keep for years.',
      '',
      'Repository files also make review and backup boring in the best way: every important change can be inspected as a normal diff.',
    ].join('\n'),
    slug: 'markdown-ownership',
    categories: ['Notes', 'Writing'],
    tags: ['Markdown', 'Repository'],
    series: ['Platform Journal'],
    viewCount: 76,
    likeCount: 9,
  },
  {
    id: 'project-taste-skill',
    title: 'Taste Skill',
    type: 'project',
    status: 'published',
    visibility: 'public',
    publishedAt: '2026-06-25',
    updatedAt: '2026-06-25',
    summary: 'Open-source agent skills that help AI-built frontend work feel more intentional, polished, and product-ready.',
    bodyMarkdown: [
      '## Why it is recommended',
      '',
      'Taste Skill packages frontend taste rules as portable agent skills, giving AI coding tools stronger layout, typography, motion, and spacing guidance.',
    ].join('\n'),
    slug: 'taste-skill',
    coverImageUrl: '/images/default-post-cover.png',
    coverAltText: 'Taste Skill project cover',
    featured: true,
    sourceType: 'repost',
    sourceUrl: 'https://github.com/Leonxlnx/taste-skill',
    categories: ['Open Source', 'AI Coding'],
    tags: ['Agent Skills', 'Frontend', 'Design Systems'],
    series: ['Open Source Recommendations'],
    project: {
      status: 'active',
      links: {
        website: 'https://www.tasteskill.dev/',
        repository: 'https://github.com/Leonxlnx/taste-skill',
      },
      stack: ['Agent Skills', 'Frontend', 'Design Systems'],
      startedAt: '2026-06-25',
    },
    viewCount: 0,
    likeCount: 0,
  },
  {
    id: 'project-trellis',
    title: 'Trellis',
    type: 'project',
    status: 'published',
    visibility: 'public',
    publishedAt: '2026-06-24',
    updatedAt: '2026-06-25',
    summary: 'An AI coding framework that stores specs, tasks, and memory in the repository.',
    bodyMarkdown: [
      '## Why it is recommended',
      '',
      'Trellis keeps AI coding sessions aligned with project standards by persisting specs, tasks, and workspace journals in the repo.',
    ].join('\n'),
    slug: 'trellis',
    featured: true,
    sourceType: 'repost',
    sourceUrl: 'https://github.com/mindfold-ai/trellis',
    categories: ['Open Source', 'AI Coding'],
    tags: ['AI Coding', 'Specs', 'Project Memory'],
    series: ['Open Source Recommendations'],
    project: {
      status: 'active',
      links: {
        website: 'https://docs.trytrellis.app/',
        repository: 'https://github.com/mindfold-ai/trellis',
      },
      stack: ['AI Coding', 'Specs', 'Project Memory'],
      startedAt: '2026-06-25',
    },
    viewCount: 0,
    likeCount: 0,
  },
  {
    id: 'project-superpowers',
    title: 'Superpowers',
    type: 'project',
    status: 'published',
    visibility: 'public',
    publishedAt: '2026-06-23',
    updatedAt: '2026-06-25',
    summary: 'A composable skills methodology for helping coding agents follow a disciplined development workflow.',
    bodyMarkdown: [
      '## Why it is recommended',
      '',
      'Superpowers gives coding agents a structured path through clarification, planning, TDD, implementation, and verification.',
    ].join('\n'),
    slug: 'superpowers',
    featured: true,
    sourceType: 'repost',
    sourceUrl: 'https://github.com/obra/Superpowers',
    categories: ['Open Source', 'AI Coding'],
    tags: ['Agent Skills', 'Workflow', 'TDD'],
    series: ['Open Source Recommendations'],
    project: {
      status: 'active',
      links: {
        repository: 'https://github.com/obra/Superpowers',
      },
      stack: ['Agent Skills', 'Workflow', 'TDD'],
      startedAt: '2026-06-25',
    },
    viewCount: 0,
    likeCount: 0,
  },
  {
    id: 'moment-first',
    title: 'The foundation is simpler now',
    type: 'moment',
    status: 'published',
    visibility: 'public',
    publishedAt: '2026-06-07',
    summary: 'The platform starts from public pages, repository content, and a small admin publishing surface.',
    bodyMarkdown: 'Today the boundary is clearer: public pages, repository files, admin publishing, and optional hosted interaction services each have their own place.',
    slug: 'first-foundation',
    categories: ['Daily'],
    tags: ['Daily', 'Architecture'],
    viewCount: 52,
    likeCount: 7,
  },
];
